CREATE TABLE IF NOT EXISTS CORE_TELA (
  ID_TELA INTEGER PRIMARY KEY,
  CODIGO_TELA TEXT NOT NULL UNIQUE,
  NOME_TELA TEXT NOT NULL,
  MODULO TEXT NOT NULL,
  CAMINHO_ROTA TEXT NOT NULL,
  ICONE TEXT,
  DESCRICAO_TELA TEXT,
  ATIVA INTEGER NOT NULL DEFAULT 1,
  DATA_CADASTRO TEXT NOT NULL DEFAULT (datetime('now')),
  DATA_ATUALIZACAO TEXT
);
