CREATE TABLE IF NOT EXISTS CORE_EMPRESA (
  ID_EMPRESA INTEGER PRIMARY KEY,
  NOME_FANTASIA TEXT NOT NULL,
  RAZAO_SOCIAL TEXT NOT NULL,
  CNPJ TEXT NOT NULL UNIQUE,
  INSCRICAO_ESTADUAL TEXT,
  INSCRICAO_MUNICIPAL TEXT,
  REGIME_TRIBUTARIO TEXT,
  LOGOTIPO_URL TEXT,
  ATIVA INTEGER NOT NULL DEFAULT 1,
  DATA_CADASTRO TEXT NOT NULL DEFAULT (datetime('now')),
  DATA_ATUALIZACAO TEXT
);
