CREATE TABLE IF NOT EXISTS CORE_AJUDA_TELA (
  ID_AJUDA INTEGER PRIMARY KEY,
  ID_TELA INTEGER NOT NULL,
  OBJETIVO_TELA TEXT,
  QUANDO_UTILIZAR TEXT,
  DESCRICAO_PROCESSO TEXT,
  PASSO_A_PASSO TEXT,
  CAMPOS_OBRIGATORIOS TEXT,
  CAMPOS_OPCIONAIS TEXT,
  REFLEXOS_PROCESSO TEXT,
  ERROS_COMUNS TEXT,
  ATIVA INTEGER NOT NULL DEFAULT 1,
  DATA_CADASTRO TEXT NOT NULL DEFAULT (datetime('now')),
  DATA_ATUALIZACAO TEXT,
  FOREIGN KEY (ID_TELA) REFERENCES CORE_TELA(ID_TELA)
);
