INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  'CADASTRO DE EMPRESA NO CRISTALCAR ERP',
  'UTILIZAR PARA CRIAR OU AJUSTAR DADOS DA EMPRESA',
  'TELA RESPONSAVEL PELO CADASTRO GERAL DA EMPRESA',
  'PREENCHER OS CAMPOS OBRIGATORIOS E CLICAR EM SALVAR',
  'NOME FANTASIA, RAZAO SOCIAL, CNPJ',
  'INSCRICAO ESTADUAL, INSCRICAO MUNICIPAL, REGIME TRIBUTARIO, LOGOTIPO, STATUS ATIVA',
  'OS DADOS CADASTRADOS AQUI SAO UTILIZADOS NA SELECAO DE EMPRESA E COMO CONTEXTO MULTIEMPRESA DO ERP',
  'ERROS MAIS COMUNS SAO CNPJ DUPLICADO OU CNPJ COM QUANTIDADE DE DIGITOS INCORRETA',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD001_CORE_EMPRESA';
