INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  'CADASTRAR E MANTER OS DADOS BASICOS DA EMPRESA NO SISTEMA CRISTALCAR ERP.',
  'UTILIZAR QUANDO FOR NECESSARIO CADASTRAR UMA NOVA EMPRESA OU AJUSTAR OS DADOS CADASTRAIS DE UMA EMPRESA EXISTENTE.',
  'TELA RESPONSAVEL POR INCLUIR E ATUALIZAR NOME FANTASIA, RAZAO SOCIAL, CNPJ, INSCRICOES, REGIME TRIBUTARIO, LOGOTIPO E STATUS ATIVA OU INATIVA.',
  'PREENCHER OS CAMPOS OBRIGATORIOS, CONFERIR AS INFORMACOES, DEFINIR SE A EMPRESA ESTA ATIVA E CLICAR EM SALVAR.',
  'NOME FANTASIA; RAZAO SOCIAL; CNPJ.',
  'INSCRICAO ESTADUAL; INSCRICAO MUNICIPAL; REGIME TRIBUTARIO; LOGOTIPO; STATUS ATIVA.',
  'OS DADOS CADASTRADOS AQUI SERAO UTILIZADOS NA TELA DE SELECAO DE EMPRESA E COMO CONTEXTO PARA TODAS AS OPERACOES MULTIEMPRESA DO ERP.',
  'ERROS MAIS COMUNS: CNPJ DIGITADO COM QUANTIDADE DE DIGITOS INCORRETA, CNPJ JA CADASTRADO PARA OUTRA EMPRESA OU EMPRESA MARCADA COMO INATIVA POR ENGANO.',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD001_CORE_EMPRESA';
