INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  'DEFINIR QUAL EMPRESA ESTA EM USO NA SESSAO DO USUARIO.',
  'UTILIZAR SEMPRE ANTES DE ACESSAR QUALQUER MODULO OU QUANDO FOR NECESSARIO TROCAR A EMPRESA EM USO.',
  'TELA INICIAL QUE LISTA AS EMPRESAS CADASTRADAS, INDICA SE ESTAO ATIVAS OU INATIVAS E PERMITE ESCOLHER QUAL EMPRESA SERA O CONTEXTO PARA AS OPERACOES.',
  'ESCOLHER UMA EMPRESA ATIVA NA LISTA E CLICAR EM SELECIONAR. APOS A ESCOLHA, TODAS AS TELAS DO ERP PASSAM A OPERAR NO CONTEXTO DESSA EMPRESA.',
  'PELO MENOS UMA EMPRESA PRECISA ESTAR CADASTRADA PARA QUE A SELECAO SEJA POSSIVEL.',
  'STATUS ATIVA OU INATIVA; LOGOTIPO; DEMAIS DADOS CADASTRAIS SAO UTILIZADOS APENAS PARA EXIBICAO.',
  'A EMPRESA SELECIONADA DEFINE O CONTEXTO MULTIEMPRESA DO ERP, AFETANDO CONSULTAS, CADASTROS E RELATORIOS.',
  'ERROS COMUNS: ACESSAR OUTRAS TELAS SEM TER SELECIONADO UMA EMPRESA OU MUDAR A EMPRESA E ESQUECER QUE O CONTEXTO FOI ALTERADO.',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CORE010_SELECAO_EMPRESA';
