INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
VALUES (
  (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'CORE010_SELECAO_EMPRESA'),
  'DEFINIR QUAL EMPRESA ESTA EM USO NA SESSAO DO USUARIO.',
  'UTILIZAR ANTES DE ACESSAR QUALQUER MODULO OU QUANDO PRECISAR TROCAR A EMPRESA EM USO.',
  'TELA INICIAL QUE LISTA AS EMPRESAS CADASTRADAS E PERMITE ESCOLHER QUAL EMPRESA SERA O CONTEXTO DAS OPERACOES.',
  'ESCOLHER UMA EMPRESA ATIVA NA LISTA E CLICAR EM SELECIONAR. APOS A ESCOLHA TODAS AS OPERACOES DO ERP PASSAM A USAR ESSA EMPRESA.',
  'PELO MENOS UMA EMPRESA PRECISA ESTAR CADASTRADA E ATIVA.',
  'STATUS ATIVA OU INATIVA LOGOTIPO E DEMAIS DADOS SAO UTILIZADOS PARA EXIBICAO.',
  'A EMPRESA SELECIONADA DEFINE O CONTEXTO MULTIEMPRESA PARA CONSULTAS CADASTROS E RELATORIOS.',
  'ERROS COMUNS SAO NAO SELECIONAR NENHUMA EMPRESA OU ESQUECER QUE A EMPRESA FOI TROCADA.',
  1
);
