-- Atualiza codigos em CORE_TELA
UPDATE CORE_TELA
SET CODIGO_TELA = 'CAD002_EMP_EMPRESA'
WHERE CODIGO_TELA = 'CAD001_CORE_EMPRESA';

UPDATE CORE_TELA
SET CODIGO_TELA = 'CAD001_EMP_SELECAO'
WHERE CODIGO_TELA = 'CORE010_SELECAO_EMPRESA';

UPDATE CORE_TELA
SET CODIGO_TELA = 'HELP000_CORE_AJUDA'
WHERE CODIGO_TELA = 'HELP000_AJUDA_GERAL';
