CREATE TABLE IF NOT EXISTS EMP_DEPARTAMENTO (
  ID_DEPARTAMENTO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EMPRESA INTEGER NOT NULL,
  NOME_DEPARTAMENTO TEXT NOT NULL,
  DESCRICAO TEXT,
  ATIVO INTEGER NOT NULL DEFAULT 1,
  DATA_CADASTRO TEXT NOT NULL DEFAULT (datetime('now')),
  DATA_ATUALIZACAO TEXT,
  FOREIGN KEY (ID_EMPRESA) REFERENCES EMP_EMPRESA (ID_EMPRESA)
);

CREATE INDEX IF NOT EXISTS IDX_EMP_DEPARTAMENTO_EMPRESA
  ON EMP_DEPARTAMENTO (ID_EMPRESA);
