INSERT OR IGNORE INTO CORE_TELA (
  ID_TELA,
  CODIGO_TELA,
  NOME_TELA,
  MODULO,
  CAMINHO_ROTA,
  ICONE,
  DESCRICAO_TELA,
  ATIVA,
  DATA_CADASTRO
) VALUES (
  3,
  'CAD003_EMP_DEPARTAMENTO',
  'CADASTRO DE DEPARTAMENTO',
  'EMPRESA',
  '/emp/departamento',
  'building-2',
  'Tela para cadastro e manutencao de departamentos por empresa.',
  1,
  datetime('now')
);

INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  'CADASTRAR E MANTER DEPARTAMENTOS VINCULADOS A CADA EMPRESA.',
  'UTILIZAR QUANDO FOR NECESSARIO CRIAR OU AJUSTAR DEPARTAMENTOS DA EMPRESA.',
  'TELA RESPONSAVEL PELO CADASTRO E MANUTENCAO DE DEPARTAMENTOS.',
  'PREENCHER OS CAMPOS OBRIGATORIOS E CLICAR EM SALVAR.',
  'NOME DO DEPARTAMENTO, EMPRESA.',
  'DESCRICAO, STATUS ATIVO.',
  'OS DEPARTAMENTOS CADASTRADOS AQUI SAO UTILIZADOS NO MODULO DE RH E EM OUTROS PROCESSOS DO ERP.',
  'ERROS COMUNS SAO NOME DEPARTAMENTO DUPLICADO NA MESMA EMPRESA.',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD003_EMP_DEPARTAMENTO';
