-- Garante que o registro da tela CAD003_EMP_DEPARTAMENTO exista
INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD003_EMP_DEPARTAMENTO';

-- Atualiza o help da tela CAD003_EMP_DEPARTAMENTO
UPDATE CORE_AJUDA_TELA
SET
  OBJETIVO_TELA = 'MANTER O CADASTRO DE DEPARTAMENTOS POR EMPRESA PARA ORGANIZAR RESPONSABILIDADES CENTROS DE CUSTO E PROCESSOS INTERNOS.',
  QUANDO_UTILIZAR = 'UTILIZAR SEMPRE QUE FOR NECESSARIO CRIAR ALTERAR OU INATIVAR UM DEPARTAMENTO DA EMPRESA SELECIONADA.',
  DESCRICAO_PROCESSO = 'ESTA TELA PERMITE CADASTRAR E MANTER OS DEPARTAMENTOS VINCULADOS A EMP_EMPRESA DEFINIR SE ESTAO ATIVOS E REGISTRAR UMA DESCRICAO DO PAPEL DE CADA DEPARTAMENTO.',
  PASSO_A_PASSO = '1 SELECIONAR A EMPRESA NA TELA INICIAL CAD001_EMP_SELECAO. 2 ACESSAR O MENU CADASTROS E ABRIR A TELA CAD003_EMP_DEPARTAMENTO. 3 INFORMAR O NOME DO DEPARTAMENTO E UMA DESCRICAO DO QUE ELE FAZ. 4 DEFINIR SE O DEPARTAMENTO ESTA ATIVO. 5 CLICAR EM SALVAR PARA REGISTRAR OU ATUALIZAR O DEPARTAMENTO. 6 A CADA SALVAMENTO UM NOVO FORMULARIO EM BRANCO FICA DISPONIVEL PARA NOVO CADASTRO.',
  CAMPOS_OBRIGATORIOS = 'NOME_DEPARTAMENTO.',
  CAMPOS_OPCIONAIS = 'DESCRICAO STATUS ATIVO (PADRAO ATIVO).',
  REFLEXOS_PROCESSO = 'OS DEPARTAMENTOS CADASTRADOS SERAO UTILIZADOS POR OUTROS MODULOS DO ERP ESPECIALMENTE RH PARA VINCULAR FUNCIONARIOS PROCESSOS E INDICADORES. ALTERACOES EM NOMES OU STATUS PODEM IMPACTAR CONSULTAS E RELATORIOS QUE UTILIZAM O DEPARTAMENTO.',
  ERROS_COMUNS = 'CADASTRAR DEPARTAMENTO SEM NOME. DUPLICAR NOME DE DEPARTAMENTO DENTRO DA MESMA EMPRESA. INATIVAR UM DEPARTAMENTO QUE AINDA ESTA VINCULADO A FUNCIONARIOS OU PROCESSOS SEM ANALISAR O IMPACTO.'
WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'CAD003_EMP_DEPARTAMENTO');
