-- Garante que o registro da tela CAD003_EMP_DEPARTAMENTO exista
INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD003_EMP_DEPARTAMENTO';

-- Atualiza o help da tela CAD003_EMP_DEPARTAMENTO
UPDATE CORE_AJUDA_TELA
SET
  OBJETIVO_TELA = 'MANTER O CADASTRO DE DEPARTAMENTOS POR EMPRESA PARA ORGANIZAR RESPONSABILIDADES CENTROS DE CUSTO E PROCESSOS INTERNOS.',
  QUANDO_UTILIZAR = 'UTILIZAR QUANDO FOR NECESSARIO CRIAR AJUSTAR OU INATIVAR UM DEPARTAMENTO DA EMPRESA SELECIONADA.',
  DESCRICAO_PROCESSO = 'TELA RESPONSAVEL PELO CADASTRO E MANUTENCAO DOS DEPARTAMENTOS VINCULADOS A EMP_EMPRESA.',
  PASSO_A_PASSO = '1 SELECIONAR A EMPRESA NA TELA CAD001_EMP_SELECAO. 2 ACESSAR O MENU CADASTROS E ABRIR CAD003_EMP_DEPARTAMENTO. 3 INFORMAR O NOME DO DEPARTAMENTO E A DESCRICAO. 4 DEFINIR SE O DEPARTAMENTO ESTA ATIVO. 5 CLICAR EM SALVAR. 6 APOS SALVAR UM NOVO FORMULARIO EM BRANCO FICA DISPONIVEL PARA OUTRO CADASTRO.',
  CAMPOS_OBRIGATORIOS = 'NOME DO DEPARTAMENTO.',
  CAMPOS_OPCIONAIS = 'DESCRICAO STATUS ATIVO.',
  REFLEXOS_PROCESSO = 'OS DEPARTAMENTOS CADASTRADOS SAO UTILIZADOS POR OUTROS MODULOS ESPECIALMENTE RH PARA VINCULAR FUNCIONARIOS E PROCESSOS. ALTERACOES EM NOME OU STATUS PODEM IMPACTAR RELATORIOS E CONTROLES QUE UTILIZAM O DEPARTAMENTO.',
  ERROS_COMUNS = 'CADASTRAR DEPARTAMENTO SEM NOME. DUPLICAR NOME DE DEPARTAMENTO NA MESMA EMPRESA. INATIVAR DEPARTAMENTO QUE AINDA ESTA VINCULADO A FUNCIONARIOS OU PROCESSOS SEM ANALISAR OS IMPACTOS.'
WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'CAD003_EMP_DEPARTAMENTO');
