-- Preenche descricao das telas principais
UPDATE CORE_TELA
SET DESCRICAO_TELA = 'CENTRAL DE AJUDA DO SISTEMA, LISTA E EXIBE OS HELPS DAS TELAS.'
WHERE CODIGO_TELA = 'HELP000_CORE_AJUDA';

UPDATE CORE_TELA
SET DESCRICAO_TELA = 'CADASTRO E MANUTENCAO DOS DEPARTAMENTOS POR EMPRESA.'
WHERE CODIGO_TELA = 'CAD003_EMP_DEPARTAMENTO';
