CREATE TABLE IF NOT EXISTS SEG_PERFIL (
  ID_PERFIL TEXT PRIMARY KEY,
  ID_EMPRESA INTEGER NOT NULL,
  NOME_PERFIL TEXT NOT NULL,
  DESCRICAO TEXT,
  ATIVO INTEGER NOT NULL DEFAULT 1,
  CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  ATUALIZADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (ID_EMPRESA) REFERENCES EMP_EMPRESA(ID_EMPRESA)
);

-- ID_PERFIL segue o formato PER-001, PER-002..., gerado pela aplicacao.
-- NOME_PERFIL e DESCRICAO devem ser armazenados sem acento e em caixa alta.
