CREATE TABLE IF NOT EXISTS SEG_PERFIL_TELA (
  ID_PERFIL TEXT NOT NULL,
  ID_TELA INTEGER NOT NULL,
  PODE_ACESSAR INTEGER NOT NULL DEFAULT 1,
  CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  ATUALIZADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (ID_PERFIL, ID_TELA),
  FOREIGN KEY (ID_PERFIL) REFERENCES SEG_PERFIL(ID_PERFIL),
  FOREIGN KEY (ID_TELA) REFERENCES CORE_TELA(ID_TELA)
);
