CREATE TABLE IF NOT EXISTS RH_JORNADA_TRABALHO (
  ID_JORNADA TEXT PRIMARY KEY,
  ID_EMPRESA INTEGER NOT NULL,
  NOME_JORNADA TEXT NOT NULL,
  DESCRICAO TEXT,
  CARGA_SEMANAL_HORAS INTEGER NOT NULL,
  HORA_ENTRADA_1 TEXT,
  HORA_SAIDA_1 TEXT,
  HORA_ENTRADA_2 TEXT,
  HORA_SAIDA_2 TEXT,
  HORA_ENTRADA_3 TEXT,
  HORA_SAIDA_3 TEXT,
  ATIVO INTEGER NOT NULL DEFAULT 1,
  CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  ATUALIZADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (ID_EMPRESA) REFERENCES EMP_EMPRESA(ID_EMPRESA)
);

-- ID_JORNADA segue o formato JOR-001, JOR-002..., gerado pela aplicacao.
