CREATE TABLE IF NOT EXISTS RH_FUNCIONARIO (
  ID_FUNCIONARIO TEXT PRIMARY KEY,
  ID_EMPRESA INTEGER NOT NULL,
  ID_DEPARTAMENTO INTEGER NOT NULL,
  ID_JORNADA TEXT,
  ID_PERFIL TEXT,
  CPF TEXT NOT NULL UNIQUE,
  NOME_COMPLETO TEXT NOT NULL,
  DATA_ADMISSAO TEXT NOT NULL,
  DATA_DEMISSAO TEXT,
  ATIVO INTEGER NOT NULL DEFAULT 1,
  OBSERVACOES TEXT,
  CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  ATUALIZADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (ID_EMPRESA) REFERENCES EMP_EMPRESA(ID_EMPRESA),
  FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES EMP_DEPARTAMENTO(ID_DEPARTAMENTO),
  FOREIGN KEY (ID_JORNADA) REFERENCES RH_JORNADA_TRABALHO(ID_JORNADA),
  FOREIGN KEY (ID_PERFIL) REFERENCES SEG_PERFIL(ID_PERFIL)
);

-- ID_FUNCIONARIO segue o formato FUN-001, FUN-002..., gerado pela aplicacao.
-- CPF deve armazenar apenas os 11 digitos numericos.
