INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  'CADASTRAR E MANTER OS DADOS DE FUNCIONARIOS NO CRISTALCAR ERP.',
  'UTILIZAR SEMPRE QUE HOUVER ADMISAO, ATUALIZACAO OU DESLIGAMENTO DE FUNCIONARIO.',
  'TELA RESPONSAVEL PELO CADASTRO GERAL DO FUNCIONARIO, VINCULANDO EMPRESA, DEPARTAMENTO, JORNADA E PERFIL DE ACESSO.',
  'PREENCHER OS CAMPOS OBRIGATORIOS, DEFINIR DEPARTAMENTO, JORNADA E PERFIL QUANDO APLICAVEL E CLICAR EM SALVAR.',
  'NOME COMPLETO, CPF, DATA ADMISAO, DEPARTAMENTO.',
  'DATA NASCIMENTO, JORNADA, PERFIL, OBSERVACOES, DATA DEMISSAO.',
  'OS DADOS DO FUNCIONARIO SAO UTILIZADOS EM RELATORIOS DE RH E NA CAMADA DE SEGURANCA FUTURA.',
  'CPF COM QUANTIDADE DE DIGITOS INCORRETA, CPF JA CADASTRADO, DEPARTAMENTO NAO INFORMADO.',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD004_RH_FUNCIONARIO';

INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  'CADASTRAR E MANTER AS JORNADAS DE TRABALHO DA EMPRESA.',
  'UTILIZAR QUANDO FOR NECESSARIO DEFINIR OU ALTERAR JORNADAS VINCULADAS A FUNCIONARIOS.',
  'TELA RESPONSAVEL PELO CADASTRO DE JORNADAS DE TRABALHO, DEFININDO CARGA HORARIA E FAIXAS DE HORARIO.',
  'DEFINIR NOME DA JORNADA, CARGA SEMANAL, HORARIOS PRINCIPAIS E CLICAR EM SALVAR.',
  'NOME JORNADA, CARGA SEMANAL.',
  'DESCRICAO, HORARIOS ADICIONAIS, STATUS ATIVO.',
  'AS JORNADAS SERAO VINCULADAS AOS FUNCIONARIOS PARA CONTROLES OPERACIONAIS FUTUROS.',
  'NAO INFORMAR A CARGA SEMANAL OU CADASTRAR JORNADAS DUPLICADAS COM O MESMO NOME.',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD005_RH_JORNADA';

INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  'CADASTRAR E MANTER OS PERFIS DE ACESSO DO SISTEMA.',
  'UTILIZAR QUANDO FOR NECESSARIO CRIAR OU AJUSTAR PERFIS E TELAS PERMITIDAS.',
  'TELA RESPONSAVEL PELO CADASTRO DE PERFIS E CONFIGURACAO DAS TELAS QUE CADA PERFIL PODE ACESSAR.',
  'CADASTRAR O PERFIL, DEFINIR SE ESTA ATIVO E CONFIGURAR AS TELAS PERMITIDAS.',
  'NOME PERFIL.',
  'DESCRICAO, STATUS ATIVO, TELAS PERMITIDAS.',
  'OS PERFIS DEFINIDOS SERAO UTILIZADOS FUTURAMENTE PARA CONTROLAR O ACESSO AS TELAS DO SISTEMA.',
  'CADASTRAR PERFIS SEM NOME OU PERFIS REDUNDANTES COM O MESMO SIGNIFICADO.',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD006_SEG_PERFIL';
