-- Renomeia o código da tela de Jornada em CORE_TELA
UPDATE CORE_TELA
   SET CODIGO_TELA = 'CAD004_RH_JORNADA'
 WHERE CODIGO_TELA = 'CAD005_RH_JORNADA';

-- Ajusta a referência da ajuda para o novo código de tela (referência por ID)
UPDATE CORE_AJUDA_TELA
   SET ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'CAD004_RH_JORNADA')
 WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'CAD005_RH_JORNADA');
