-- Garante o registro da tela CAD005_RH_FUNCIONARIO e seu respectivo help.
INSERT OR REPLACE INTO CORE_TELA (
  ID_TELA,
  CODIGO_TELA,
  NOME_TELA,
  MODULO,
  CAMINHO_ROTA,
  ICONE,
  DESCRICAO_TELA,
  ATIVA,
  DATA_CADASTRO,
  DATA_ATUALIZACAO
)
VALUES (
  (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'CAD005_RH_FUNCIONARIO'),
  'CAD005_RH_FUNCIONARIO',
  'CADASTRO DE FUNCIONARIO',
  'RH',
  '/rh/funcionario',
  'id-badge-2',
  'CADASTRO E MANUTENCAO DE FUNCIONARIOS POR EMPRESA',
  1,
  COALESCE(
    (SELECT DATA_CADASTRO FROM CORE_TELA WHERE CODIGO_TELA = 'CAD005_RH_FUNCIONARIO'),
    datetime('now')
  ),
  (SELECT DATA_ATUALIZACAO FROM CORE_TELA WHERE CODIGO_TELA = 'CAD005_RH_FUNCIONARIO')
);

INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA,
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA,
  DATA_CADASTRO,
  DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = t.ID_TELA),
  t.ID_TELA,
  'CADASTRAR E MANTER OS DADOS DE FUNCIONARIOS NO CRISTALCAR ERP.',
  'UTILIZAR QUANDO FOR NECESSARIO INCLUIR OU ATUALIZAR DADOS DE FUNCIONARIO DA EMPRESA.',
  'TELA RESPONSAVEL PELO CADASTRO GERAL DO FUNCIONARIO E SEUS VINCULOS DEPARTAMENTO JORNADA E PERFIL DE ACESSO.',
  'PREENCHER OS CAMPOS OBRIGATORIOS, DEFINIR DEPARTAMENTO, JORNADA E PERFIL QUANDO APLICAVEL E CLICAR EM SALVAR.',
  'NOME COMPLETO, CPF, DEPARTAMENTO, JORNADA, DATA DE ADMISAO.',
  'PERFIL DE ACESSO, DATA DE DESLIGAMENTO.',
  'OS DADOS DO FUNCIONARIO SERAO UTILIZADOS EM ROTINAS DE RH E CONTROLE FUTURO DE ACESSO.',
  'CPF JA CADASTRADO PARA A EMPRESA, CPF COM QUANTIDADE DE DIGITOS INVALIDA, DATAS DE ADMISAO E DESLIGAMENTO INCONSISTENTES.',
  1,
  COALESCE(
    (SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = t.ID_TELA),
    datetime('now')
  ),
  (SELECT DATA_ATUALIZACAO FROM CORE_AJUDA_TELA WHERE ID_TELA = t.ID_TELA)
FROM CORE_TELA t
WHERE t.CODIGO_TELA = 'CAD005_RH_FUNCIONARIO';
