-- Ajustes e garantia de cadastro da tela CAD006_SEG_PERFIL

UPDATE CORE_TELA
SET NOME_TELA = 'CADASTRO DE PERFIL DE ACESSO',
    MODULO = 'SEGURANCA',
    CAMINHO_ROTA = '/seg/perfil',
    DESCRICAO_TELA = 'CADASTRO E CONFIGURACAO DE PERFIS E TELAS PERMITIDAS',
    ATIVA = 1,
    DATA_ATUALIZACAO = datetime('now')
WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL';

INSERT OR IGNORE INTO CORE_TELA (
  ID_TELA,
  CODIGO_TELA,
  NOME_TELA,
  MODULO,
  CAMINHO_ROTA,
  ICONE,
  DESCRICAO_TELA,
  ATIVA,
  DATA_CADASTRO
)
SELECT
  (SELECT IFNULL(MAX(ID_TELA), 0) + 1 FROM CORE_TELA),
  'CAD006_SEG_PERFIL',
  'CADASTRO DE PERFIL DE ACESSO',
  'SEGURANCA',
  '/seg/perfil',
  'shield-lock',
  'CADASTRO E CONFIGURACAO DE PERFIS E TELAS PERMITIDAS',
  1,
  datetime('now')
WHERE NOT EXISTS (
  SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL'
);

UPDATE CORE_AJUDA_TELA
SET OBJETIVO_TELA = 'CADASTRAR E MANTER OS PERFIS DE ACESSO DO CRISTALCAR ERP.',
    QUANDO_UTILIZAR = 'UTILIZAR QUANDO FOR NECESSARIO DEFINIR OU AJUSTAR PERFIS E TELAS PERMITIDAS.',
    DESCRICAO_PROCESSO = 'TELA RESPONSAVEL PELO CADASTRO DOS PERFIS DE ACESSO E SUAS AUTORIZACOES POR TELA.',
    PASSO_A_PASSO = 'CRIAR OU EDITAR O PERFIL, DEFINIR SE ESTA ATIVO E CONFIGURAR AS TELAS QUE O PERFIL PODE ACESSAR.',
    CAMPOS_OBRIGATORIOS = 'NOME DO PERFIL.',
    CAMPOS_OPCIONAIS = 'DESCRICAO, STATUS ATIVO, TELAS PERMITIDAS.',
    REFLEXOS_PROCESSO = 'OS PERFIS DEFINIDOS AQUI SERAO UTILIZADOS POSTERIORMENTE PARA CONTROLAR O ACESSO AS TELAS DO SISTEMA.',
    ERROS_COMUNS = 'CADASTRAR PERFIS COM MESMO SIGNIFICADO, DEIXAR PERFIS SEM TELAS ASSOCIADAS QUANDO DEVERIAM TER ACESSO.',
    ATIVA = 1,
    DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL');

INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  'CADASTRAR E MANTER OS PERFIS DE ACESSO DO CRISTALCAR ERP.',
  'UTILIZAR QUANDO FOR NECESSARIO DEFINIR OU AJUSTAR PERFIS E TELAS PERMITIDAS.',
  'TELA RESPONSAVEL PELO CADASTRO DOS PERFIS DE ACESSO E SUAS AUTORIZACOES POR TELA.',
  'CRIAR OU EDITAR O PERFIL, DEFINIR SE ESTA ATIVO E CONFIGURAR AS TELAS QUE O PERFIL PODE ACESSAR.',
  'NOME DO PERFIL.',
  'DESCRICAO, STATUS ATIVO, TELAS PERMITIDAS.',
  'OS PERFIS DEFINIDOS AQUI SERAO UTILIZADOS POSTERIORMENTE PARA CONTROLAR O ACESSO AS TELAS DO SISTEMA.',
  'CADASTRAR PERFIS COM MESMO SIGNIFICADO, DEIXAR PERFIS SEM TELAS ASSOCIADAS QUANDO DEVERIAM TER ACESSO.',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD006_SEG_PERFIL'
  AND NOT EXISTS (
    SELECT 1
    FROM CORE_AJUDA_TELA H
    WHERE H.ID_TELA = T.ID_TELA
  );
