ALTER TABLE SEG_PERFIL_TELA ADD COLUMN PODE_CONSULTAR INTEGER NOT NULL DEFAULT 0;
ALTER TABLE SEG_PERFIL_TELA ADD COLUMN PODE_EDITAR INTEGER NOT NULL DEFAULT 0;

UPDATE SEG_PERFIL_TELA
SET PODE_CONSULTAR = 1,
    PODE_EDITAR = 1
WHERE PODE_ACESSAR = 1;
