WITH TELA AS (
  SELECT ID_TELA
  FROM CORE_TELA
  WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL'
)
UPDATE CORE_AJUDA_TELA
SET OBJETIVO_TELA = 'CONFIGURAR OS PERFIS DE ACESSO E AS PERMISSOES DE CADA TELA DO SISTEMA.',
    QUANDO_UTILIZAR = 'UTILIZAR QUANDO FOR NECESSARIO CRIAR, AJUSTAR OU REVISAR OS PERFIS DE ACESSO DOS USUARIOS, DEFININDO QUAIS TELAS CADA PERFIL PODE ACESSAR, CONSULTAR OU EDITAR.',
    DESCRICAO_PROCESSO = 'TELA RESPONSAVEL PELO CADASTRO DOS PERFIS DE ACESSO (SEGURANCA) E PELA CONFIGURACAO DAS PERMISSOES POR TELA. A PARTIR DESTE CADASTRO SERAO DEFINIDOS OS DIREITOS DE ACESSO QUE SERAO APLICADOS AOS FUNCIONARIOS VINCULADOS AO PERFIL.',
    PASSO_A_PASSO = 'SELECIONAR UM PERFIL NA LISTA DE PERFIS CADASTRADOS.\n\nCLICAR NO BOTAO EDITAR PARA AJUSTAR OS DADOS GERAIS DO PERFIL (NOME, DESCRICAO, STATUS), SE NECESSARIO.\n\nCLICAR NO BOTAO EDITAR ACOES PARA ABRIR A AREA DE CONFIGURACAO DAS TELAS PERMITIDAS PARA O PERFIL SELECIONADO.\n\nPARA CADA MODULO (CORE, EMPRESA, RH, SEGURANCA), ANALISAR A LISTA DE TELAS DISPONIVEIS.\n\nPARA CADA TELA, DEFINIR AS PERMISSOES MARCANDO AS OPCOES:\n\nPODE ACESSAR: LIBERA A TELA PARA O PERFIL.\n\nPODE CONSULTAR: PERMITE APENAS VISUALIZAR AS INFORMACOES DA TELA.\n\nPODE EDITAR: PERMITE INCLUIR, ALTERAR E EXCLUIR DADOS NA TELA.\n\nLEMBRE-SE DAS REGRAS:\n\nSE PODE EDITAR ESTIVER MARCADO, PODE ACESSAR E PODE CONSULTAR DEVEM PERMANECER MARCADOS.\n\nSE PODE ACESSAR FOR DESMARCADO, AS OPCOES CONSULTAR E EDITAR DEVEM SER AUTOMATICAMENTE DESMARCADAS.\n\nAPOS REALIZAR OS AJUSTES, CLICAR EM SALVAR ACESSOS DO PERFIL PARA APLICAR AS PERMISSOES.\n\nSE TIVER FEITO ALGUMA SELECAO POR ENGANO, UTILIZAR O BOTAO CANCELAR PARA DESCARTAR AS ALTERACOES E RECARREGAR AS PERMISSOES ORIGINAIS.',
    CAMPOS_OBRIGATORIOS = 'NOME DO PERFIL, STATUS, E PELO MENOS UMA TELA COM PERMISSAO PODE ACESSAR PARA QUE O PERFIL TENHA UTILIDADE NA OPERACAO.',
    CAMPOS_OPCIONAIS = 'DESCRICAO DO PERFIL E AJUSTES FINOS DE PERMISSAO (APENAS CONSULTA OU COM EDICAO).',
    REFLEXOS_PROCESSO = 'AS PERMISSOES DEFINIDAS NESTA TELA CONTROLAM O QUE CADA FUNCIONARIO PODERA EXECUTAR NO SISTEMA, DE ACORDO COM O PERFIL VINCULADO AO SEU CADASTRO.\nUM FUNCIONARIO COM PERFIL QUE POSSUI APENAS PODE CONSULTAR EM UMA TELA CONSEGUE VISUALIZAR OS DADOS, MAS NAO CONSEGUE EDITAR.\nJA UM FUNCIONARIO COM PERFIL QUE POSSUI PODE EDITAR TERA ACESSO COMPLETO DE EDICAO (DENTRO DAS REGRAS DEFINIDAS PARA A TELA).\nESSA CONFIGURACAO SERA A BASE PARA O CONTROLE DE SEGURANCA QUANDO O LOGIN DE USUARIO FOR IMPLANTADO.',
    ERROS_COMUNS = 'CRIAR UM PERFIL E ESQUECER DE MARCAR AS TELAS EM PODE ACESSAR, IMPEDINDO O USO DO PERFIL NA PRATICA.\n\nMARCAR PODE EDITAR PARA TELAS EM QUE O PERFIL DEVERIA TER APENAS CONSULTA.\n\nAJUSTAR PERMISSOES DE TELA E ESQUECER DE CLICAR EM SALVAR ACESSOS DO PERFIL.\n\nVINCULAR FUNCIONARIO A UM PERFIL INCORRETO, LIBERANDO ACESSO OU EDICAO INDEVIDA EM ALGUMA AREA DO SISTEMA.',
    ATIVA = 1,
    DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM TELA)
  AND EXISTS (SELECT 1 FROM TELA);

INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  'CONFIGURAR OS PERFIS DE ACESSO E AS PERMISSOES DE CADA TELA DO SISTEMA.',
  'UTILIZAR QUANDO FOR NECESSARIO CRIAR, AJUSTAR OU REVISAR OS PERFIS DE ACESSO DOS USUARIOS, DEFININDO QUAIS TELAS CADA PERFIL PODE ACESSAR, CONSULTAR OU EDITAR.',
  'TELA RESPONSAVEL PELO CADASTRO DOS PERFIS DE ACESSO (SEGURANCA) E PELA CONFIGURACAO DAS PERMISSOES POR TELA. A PARTIR DESTE CADASTRO SERAO DEFINIDOS OS DIREITOS DE ACESSO QUE SERAO APLICADOS AOS FUNCIONARIOS VINCULADOS AO PERFIL.',
  'SELECIONAR UM PERFIL NA LISTA DE PERFIS CADASTRADOS.\n\nCLICAR NO BOTAO EDITAR PARA AJUSTAR OS DADOS GERAIS DO PERFIL (NOME, DESCRICAO, STATUS), SE NECESSARIO.\n\nCLICAR NO BOTAO EDITAR ACOES PARA ABRIR A AREA DE CONFIGURACAO DAS TELAS PERMITIDAS PARA O PERFIL SELECIONADO.\n\nPARA CADA MODULO (CORE, EMPRESA, RH, SEGURANCA), ANALISAR A LISTA DE TELAS DISPONIVEIS.\n\nPARA CADA TELA, DEFINIR AS PERMISSOES MARCANDO AS OPCOES:\n\nPODE ACESSAR: LIBERA A TELA PARA O PERFIL.\n\nPODE CONSULTAR: PERMITE APENAS VISUALIZAR AS INFORMACOES DA TELA.\n\nPODE EDITAR: PERMITE INCLUIR, ALTERAR E EXCLUIR DADOS NA TELA.\n\nLEMBRE-SE DAS REGRAS:\n\nSE PODE EDITAR ESTIVER MARCADO, PODE ACESSAR E PODE CONSULTAR DEVEM PERMANECER MARCADOS.\n\nSE PODE ACESSAR FOR DESMARCADO, AS OPCOES CONSULTAR E EDITAR DEVEM SER AUTOMATICAMENTE DESMARCADAS.\n\nAPOS REALIZAR OS AJUSTES, CLICAR EM SALVAR ACESSOS DO PERFIL PARA APLICAR AS PERMISSOES.\n\nSE TIVER FEITO ALGUMA SELECAO POR ENGANO, UTILIZAR O BOTAO CANCELAR PARA DESCARTAR AS ALTERACOES E RECARREGAR AS PERMISSOES ORIGINAIS.',
  'NOME DO PERFIL, STATUS, E PELO MENOS UMA TELA COM PERMISSAO PODE ACESSAR PARA QUE O PERFIL TENHA UTILIDADE NA OPERACAO.',
  'DESCRICAO DO PERFIL E AJUSTES FINOS DE PERMISSAO (APENAS CONSULTA OU COM EDICAO).',
  'AS PERMISSOES DEFINIDAS NESTA TELA CONTROLAM O QUE CADA FUNCIONARIO PODERA EXECUTAR NO SISTEMA, DE ACORDO COM O PERFIL VINCULADO AO SEU CADASTRO.\nUM FUNCIONARIO COM PERFIL QUE POSSUI APENAS PODE CONSULTAR EM UMA TELA CONSEGUE VISUALIZAR OS DADOS, MAS NAO CONSEGUE EDITAR.\nJA UM FUNCIONARIO COM PERFIL QUE POSSUI PODE EDITAR TERA ACESSO COMPLETO DE EDICAO (DENTRO DAS REGRAS DEFINIDAS PARA A TELA).\nESSA CONFIGURACAO SERA A BASE PARA O CONTROLE DE SEGURANCA QUANDO O LOGIN DE USUARIO FOR IMPLANTADO.',
  'CRIAR UM PERFIL E ESQUECER DE MARCAR AS TELAS EM PODE ACESSAR, IMPEDINDO O USO DO PERFIL NA PRATICA.\n\nMARCAR PODE EDITAR PARA TELAS EM QUE O PERFIL DEVERIA TER APENAS CONSULTA.\n\nAJUSTAR PERMISSOES DE TELA E ESQUECER DE CLICAR EM SALVAR ACESSOS DO PERFIL.\n\nVINCULAR FUNCIONARIO A UM PERFIL INCORRETO, LIBERANDO ACESSO OU EDICAO INDEVIDA EM ALGUMA AREA DO SISTEMA.',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD006_SEG_PERFIL'
  AND NOT EXISTS (
    SELECT 1 FROM CORE_AJUDA_TELA H WHERE H.ID_TELA = T.ID_TELA
  );
