WITH TELA AS (
  SELECT ID_TELA
  FROM CORE_TELA
  WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL'
)
UPDATE CORE_AJUDA_TELA
SET OBJETIVO_TELA = 'CADASTRAR PERFIS E CONTROLAR RAPIDAMENTE O QUE CADA PERFIL PODE ACESSAR, CONSULTAR OU EDITAR NAS TELAS.',
    QUANDO_UTILIZAR = '- CRIAR NOVOS PERFIS DE ACESSO.\n- AJUSTAR PERMISSOES AO ADMITIR OU DESLIGAR COLABORADORES.\n- REVISAR PERFIS EM AUDITORIAS DE SEGURANCA.',
    DESCRICAO_PROCESSO = 'TELA DIVIDIDA EM DUAS AREAS: PERFIS CADASTRADOS (NOME, DESCRICAO, STATUS E COLUNA CONSULTA PARA VER AS PERMISSOES) E TELAS PERMITIDAS PARA O PERFIL SELECIONADO (MAPA DE ACOES POR TELA).',
    PASSO_A_PASSO = '1) SELECIONAR OU CRIAR UM PERFIL\n- USE A COLUNA CONSULTA (RADIO) PARA APENAS VISUALIZAR AS PERMISSOES DO PERFIL.\n- CLIQUE EM EDITAR PARA AJUSTAR OS DADOS E HABILITAR A EDICAO DAS PERMISSOES.\n\n2) CONFIGURAR PERMISSOES POR TELA\n- PODE ACESSAR: LIBERA A ENTRADA NA TELA.\n- PODE CONSULTAR: PERMITE SOMENTE VISUALIZAR DADOS.\n- PODE EDITAR: PERMITE INCLUIR/ALTERAR/EXCLUIR E NORMALMENTE IMPLICA PODER CONSULTAR.\n\n3) SALVAR OU CANCELAR\n- SALVAR ACESSOS DO PERFIL PARA GRAVAR OS AJUSTES.\n- CANCELAR PARA DESCARTAR AS MUDANCAS E VOLTAR AO MAPA ORIGINAL.',
    CAMPOS_OBRIGATORIOS = 'NOME DO PERFIL E STATUS. O CODIGO (FORMATO PER-XXX) E GERADO AUTOMATICAMENTE.',
    CAMPOS_OPCIONAIS = 'DESCRICAO DO PERFIL E AJUSTES FINOS DE PERMISSAO CONFORME A NECESSIDADE.',
    REFLEXOS_PROCESSO = 'AS PERMISSOES DEFINIDAS AQUI DETERMINAM O QUE CADA USUARIO (VIA PERFIL) CONSEGUE VER OU EDITAR EM TODAS AS TELAS.\nREVISE PERFIS EM CONJUNTO COM O RH E A ADMINISTRACAO DO SISTEMA PARA MANTER A SEGURANCA E CONFORMIDADE.',
    ERROS_COMUNS = 'LIBERAR PODE EDITAR PARA QUEM DEVERIA APENAS CONSULTAR.\nESQUECER DE MARCAR PODE ACESSAR, BLOQUEANDO A TELA MESMO COM CONSULTA OU EDICAO MARCADOS.\nNAO SALVAR AS ALTERACOES APOS AJUSTAR PERMISSOES.',
    ATIVA = 1,
    DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM TELA)
  AND EXISTS (SELECT 1 FROM TELA);

INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  'CADASTRAR PERFIS E CONTROLAR RAPIDAMENTE O QUE CADA PERFIL PODE ACESSAR, CONSULTAR OU EDITAR NAS TELAS.',
  '- CRIAR NOVOS PERFIS DE ACESSO.\n- AJUSTAR PERMISSOES AO ADMITIR OU DESLIGAR COLABORADORES.\n- REVISAR PERFIS EM AUDITORIAS DE SEGURANCA.',
  'TELA DIVIDIDA EM DUAS AREAS: PERFIS CADASTRADOS (NOME, DESCRICAO, STATUS E COLUNA CONSULTA PARA VER AS PERMISSOES) E TELAS PERMITIDAS PARA O PERFIL SELECIONADO (MAPA DE ACOES POR TELA).',
  '1) SELECIONAR OU CRIAR UM PERFIL\n- USE A COLUNA CONSULTA (RADIO) PARA APENAS VISUALIZAR AS PERMISSOES DO PERFIL.\n- CLIQUE EM EDITAR PARA AJUSTAR OS DADOS E HABILITAR A EDICAO DAS PERMISSOES.\n\n2) CONFIGURAR PERMISSOES POR TELA\n- PODE ACESSAR: LIBERA A ENTRADA NA TELA.\n- PODE CONSULTAR: PERMITE SOMENTE VISUALIZAR DADOS.\n- PODE EDITAR: PERMITE INCLUIR/ALTERAR/EXCLUIR E NORMALMENTE IMPLICA PODER CONSULTAR.\n\n3) SALVAR OU CANCELAR\n- SALVAR ACESSOS DO PERFIL PARA GRAVAR OS AJUSTES.\n- CANCELAR PARA DESCARTAR AS MUDANCAS E VOLTAR AO MAPA ORIGINAL.',
  'NOME DO PERFIL E STATUS. O CODIGO (FORMATO PER-XXX) E GERADO AUTOMATICAMENTE.',
  'DESCRICAO DO PERFIL E AJUSTES FINOS DE PERMISSAO CONFORME A NECESSIDADE.',
  'AS PERMISSOES DEFINIDAS AQUI DETERMINAM O QUE CADA USUARIO (VIA PERFIL) CONSEGUE VER OU EDITAR EM TODAS AS TELAS.\nREVISE PERFIS EM CONJUNTO COM O RH E A ADMINISTRACAO DO SISTEMA PARA MANTER A SEGURANCA E CONFORMIDADE.',
  'LIBERAR PODE EDITAR PARA QUEM DEVERIA APENAS CONSULTAR.\nESQUECER DE MARCAR PODE ACESSAR, BLOQUEANDO A TELA MESMO COM CONSULTA OU EDICAO MARCADOS.\nNAO SALVAR AS ALTERACOES APOS AJUSTAR PERMISSOES.',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD006_SEG_PERFIL'
  AND NOT EXISTS (
    SELECT 1 FROM CORE_AJUDA_TELA H WHERE H.ID_TELA = T.ID_TELA
  );
