WITH TELA AS (
  SELECT ID_TELA
  FROM CORE_TELA
  WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL'
)
UPDATE CORE_AJUDA_TELA
SET OBJETIVO_TELA = 'CONFIGURAR O QUE CADA PERFIL PODE ACESSAR, CONSULTAR OU EDITAR EM CADA TELA.',
    QUANDO_UTILIZAR = '- DEFINIR PERMISSOES AO CRIAR UM NOVO PERFIL.\n- AJUSTAR ACESSOS QUANDO COLABORADORES MUDAM DE FUNCAO.\n- REVISAR PERFIS PERIODICAMENTE PARA AUDITORIA.',
    DESCRICAO_PROCESSO = 'UTILIZE A SECAO "TELAS PERMITIDAS PARA O PERFIL SELECIONADO" PARA MAPEAR AS ACOES PERMITIDAS EM CADA MODULO (CORE, EMPRESA, RH, SEGURANCA). A LISTA MOSTRA COLUNAS FIXAS: CODIGO DA TELA, NOME DA TELA, PODE ACESSAR, PODE CONSULTAR E PODE EDITAR.',
    PASSO_A_PASSO = '1) ESCOLHER UM PERFIL NA LISTA SUPERIOR OU CRIAR UM NOVO.\n2) NA SECAO TELAS PERMITIDAS, AJUSTAR AS COLUNAS DE PERMISSAO:\n- PODE ACESSAR: LIBERA O ACESSO A TELA.\n- PODE CONSULTAR: PERMITE APENAS VISUALIZAR.\n- PODE EDITAR: LIBERA INCLUIR/ALTERAR/EXCLUIR E DEPENDE DE PODER ACESSAR.\n3) SALVAR ACESSOS DO PERFIL PARA GRAVAR AS MUDANCAS OU CANCELAR PARA DESCARTAR.',
    CAMPOS_OBRIGATORIOS = 'NOME DO PERFIL E STATUS (ATIVO/INATIVO). O CODIGO E GERADO AUTOMATICAMENTE NO FORMATO PER-XXX.',
    CAMPOS_OPCIONAIS = 'DESCRICAO DO PERFIL E AJUSTES FINOS DE PERMISSAO POR TELA.',
    REFLEXOS_PROCESSO = 'AS CONFIGURACOES IMPACTAM TODAS AS TELAS DO ERP PARA USUARIOS COM ESSE PERFIL. MANTENHA AS PERMISSOES ALINHADAS COM POLITICAS INTERNAS DE SEGURANCA.',
    ERROS_COMUNS = 'ESQUECER DE MARCAR PODE ACESSAR, BLOQUEANDO A ENTRADA NA TELA.\nLIBERAR PODE EDITAR PARA QUEM DEVERIA APENAS CONSULTAR.\nNAO SALVAR AS ALTERACOES APOS AJUSTAR PERMISSOES.',
    ATIVA = 1,
    DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM TELA)
  AND EXISTS (SELECT 1 FROM TELA);

INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  'CONFIGURAR O QUE CADA PERFIL PODE ACESSAR, CONSULTAR OU EDITAR EM CADA TELA.',
  '- DEFINIR PERMISSOES AO CRIAR UM NOVO PERFIL.\n- AJUSTAR ACESSOS QUANDO COLABORADORES MUDAM DE FUNCAO.\n- REVISAR PERFIS PERIODICAMENTE PARA AUDITORIA.',
  'UTILIZE A SECAO "TELAS PERMITIDAS PARA O PERFIL SELECIONADO" PARA MAPEAR AS ACOES PERMITIDAS EM CADA MODULO (CORE, EMPRESA, RH, SEGURANCA). A LISTA MOSTRA COLUNAS FIXAS: CODIGO DA TELA, NOME DA TELA, PODE ACESSAR, PODE CONSULTAR E PODE EDITAR.',
  '1) ESCOLHER UM PERFIL NA LISTA SUPERIOR OU CRIAR UM NOVO.\n2) NA SECAO TELAS PERMITIDAS, AJUSTAR AS COLUNAS DE PERMISSAO:\n- PODE ACESSAR: LIBERA O ACESSO A TELA.\n- PODE CONSULTAR: PERMITE APENAS VISUALIZAR.\n- PODE EDITAR: LIBERA INCLUIR/ALTERAR/EXCLUIR E DEPENDE DE PODER ACESSAR.\n3) SALVAR ACESSOS DO PERFIL PARA GRAVAR AS MUDANCAS OU CANCELAR PARA DESCARTAR.',
  'NOME DO PERFIL E STATUS (ATIVO/INATIVO). O CODIGO E GERADO AUTOMATICAMENTE NO FORMATO PER-XXX.',
  'DESCRICAO DO PERFIL E AJUSTES FINOS DE PERMISSAO POR TELA.',
  'AS CONFIGURACOES IMPACTAM TODAS AS TELAS DO ERP PARA USUARIOS COM ESSE PERFIL. MANTENHA AS PERMISSOES ALINHADAS COM POLITICAS INTERNAS DE SEGURANCA.',
  'ESQUECER DE MARCAR PODE ACESSAR, BLOQUEANDO A ENTRADA NA TELA.\nLIBERAR PODE EDITAR PARA QUEM DEVERIA APENAS CONSULTAR.\nNAO SALVAR AS ALTERACOES APOS AJUSTAR PERMISSOES.',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD006_SEG_PERFIL'
  AND NOT EXISTS (
    SELECT 1 FROM CORE_AJUDA_TELA H WHERE H.ID_TELA = T.ID_TELA
  );
