WITH TELA AS (
  SELECT ID_TELA
  FROM CORE_TELA
  WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL'
)
UPDATE CORE_AJUDA_TELA
SET OBJETIVO_TELA = 'DEFINIR DE FORMA OBJETIVA AS PERMISSOES DE ACESSO, CONSULTA E EDICAO DE CADA PERFIL.',
    QUANDO_UTILIZAR = '- CONFIGURAR UM NOVO PERFIL DE ACESSO.\n- REVISAR OU AJUSTAR PERMISSOES EXISTENTES.',
    DESCRICAO_PROCESSO = 'USE A LISTA DE TELAS POR MODULO PARA LIBERAR APENAS O QUE O PERFIL PODE ACESSAR, CONSULTAR OU EDITAR.',
    PASSO_A_PASSO = '1) SELECIONAR UM PERFIL NA LISTA SUPERIOR.\n2) CLICAR EM "EDITAR" PARA HABILITAR A ALTERACAO DE DADOS E PERMISSOES.\n3) EM "TELAS PERMITIDAS", DEFINIR AS COLUNAS:\n- PODE ACESSAR: LIBERA A TELA PARA O PERFIL.\n- PODE CONSULTAR: PERMITE SOMENTE VISUALIZAR.\n- PODE EDITAR: AUTORIZA INCLUIR/ALTERAR/EXCLUIR REGISTROS.\n4) SALVAR OS ACESSOS PARA APLICAR AS REGRAS AOS FUNCIONARIOS DO PERFIL.',
    CAMPOS_OBRIGATORIOS = 'NOME DO PERFIL E STATUS (ATIVO/INATIVO). O CODIGO E GERADO AUTOMATICAMENTE.',
    CAMPOS_OPCIONAIS = 'DESCRICAO DO PERFIL E AJUSTES FINOS DE PERMISSAO POR TELA.',
    REFLEXOS_PROCESSO = 'AS PERMISSOES DEFINIDAS SAO APLICADAS A TODOS OS FUNCIONARIOS QUE UTILIZAM O PERFIL.',
    ERROS_COMUNS = 'ESQUECER DE ATIVAR "PODE ACESSAR" AO CONCEDER CONSULTA/EDICAO.\nNAO SALVAR AS ALTERACOES APOS AJUSTAR PERMISSOES.\nPERMITIR EDICAO PARA QUEM DEVERIA APENAS CONSULTAR.',
    ATIVA = 1,
    DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM TELA)
  AND EXISTS (SELECT 1 FROM TELA);

INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA
)
SELECT
  T.ID_TELA,
  'DEFINIR DE FORMA OBJETIVA AS PERMISSOES DE ACESSO, CONSULTA E EDICAO DE CADA PERFIL.',
  '- CONFIGURAR UM NOVO PERFIL DE ACESSO.\n- REVISAR OU AJUSTAR PERMISSOES EXISTENTES.',
  'USE A LISTA DE TELAS POR MODULO PARA LIBERAR APENAS O QUE O PERFIL PODE ACESSAR, CONSULTAR OU EDITAR.',
  '1) SELECIONAR UM PERFIL NA LISTA SUPERIOR.\n2) CLICAR EM "EDITAR" PARA HABILITAR A ALTERACAO DE DADOS E PERMISSOES.\n3) EM "TELAS PERMITIDAS", DEFINIR AS COLUNAS:\n- PODE ACESSAR: LIBERA A TELA PARA O PERFIL.\n- PODE CONSULTAR: PERMITE SOMENTE VISUALIZAR.\n- PODE EDITAR: AUTORIZA INCLUIR/ALTERAR/EXCLUIR REGISTROS.\n4) SALVAR OS ACESSOS PARA APLICAR AS REGRAS AOS FUNCIONARIOS DO PERFIL.',
  'NOME DO PERFIL E STATUS (ATIVO/INATIVO). O CODIGO E GERADO AUTOMATICAMENTE.',
  'DESCRICAO DO PERFIL E AJUSTES FINOS DE PERMISSAO POR TELA.',
  'AS PERMISSOES DEFINIDAS SAO APLICADAS A TODOS OS FUNCIONARIOS QUE UTILIZAM O PERFIL.',
  'ESQUECER DE ATIVAR "PODE ACESSAR" AO CONCEDER CONSULTA/EDICAO.\nNAO SALVAR AS ALTERACOES APOS AJUSTAR PERMISSOES.\nPERMITIR EDICAO PARA QUEM DEVERIA APENAS CONSULTAR.',
  1
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD006_SEG_PERFIL'
  AND NOT EXISTS (
    SELECT 1 FROM CORE_AJUDA_TELA H WHERE H.ID_TELA = T.ID_TELA
  );
