-- Adiciona colunas de remuneracao ao funcionario
ALTER TABLE RH_FUNCIONARIO
  ADD COLUMN SALARIO_BASE NUMERIC(15,2) DEFAULT 0 NOT NULL;

ALTER TABLE RH_FUNCIONARIO
  ADD COLUMN TIPO_SALARIO TEXT DEFAULT 'MENSALISTA' NOT NULL;

ALTER TABLE RH_FUNCIONARIO
  ADD COLUMN CARGA_HORARIA_MENSAL_REFERENCIA INTEGER DEFAULT 220 NOT NULL;

-- Garante consistencia para registros existentes
UPDATE RH_FUNCIONARIO
   SET SALARIO_BASE = COALESCE(SALARIO_BASE, 0),
       TIPO_SALARIO = COALESCE(TIPO_SALARIO, 'MENSALISTA'),
       CARGA_HORARIA_MENSAL_REFERENCIA = COALESCE(CARGA_HORARIA_MENSAL_REFERENCIA, 220);
