WITH TELA AS (
  SELECT ID_TELA
  FROM CORE_TELA
  WHERE CODIGO_TELA = 'CAD005_RH_FUNCIONARIO'
)
UPDATE CORE_AJUDA_TELA
SET OBJETIVO_TELA = 'CONFIGURAR OS DADOS CADASTRAIS E DE REMUNERACAO DOS FUNCIONARIOS.',
    QUANDO_UTILIZAR = 'UTILIZAR SEMPRE QUE FOR NECESSARIO INCLUIR, AJUSTAR OU CONSULTAR OS DADOS DOS FUNCIONARIOS, INCLUSIVE JORNADA DE TRABALHO E INFORMACOES DE SALARIO.',
    DESCRICAO_PROCESSO = 'TELA RESPONSAVEL PELO CADASTRO DOS FUNCIONARIOS DA EMPRESA. PERMITE INFORMAR DADOS BASICOS (NOME, DOCUMENTOS, DEPARTAMENTO, JORNADA DE TRABALHO) E OS DADOS DE REMUNERACAO (TIPO DE SALARIO, SALARIO BASE E CARGA HORARIA MENSAL DE REFERENCIA). ESTES CAMPOS SERAO UTILIZADOS POSTERIORMENTE PARA EMISSAO DO CARTAO PONTO E CALCULO DE HORAS EXTRAS.',
    PASSO_A_PASSO = '1) INFORMAR OS DADOS BASICOS DO FUNCIONARIO (NOME, DOCUMENTOS, CONTATO).\n2) SELECIONAR O DEPARTAMENTO E, SE APLICAVEL, A JORNADA DE TRABALHO PADRAO.\n3) NA SECAO DE REMUNERACAO, DEFINIR O TIPO DE SALARIO (ATUALMENTE MENSALISTA), INFORMAR O SALARIO BASE E A CARGA HORARIA MENSAL DE REFERENCIA (EX.: 220 HORAS).\n4) MARCAR SE O FUNCIONARIO ESTA ATIVO OU INATIVO.\n5) CLICAR EM SALVAR PARA GRAVAR AS INFORMACOES.\n6) UTILIZAR ESTA TELA SEMPRE QUE PRECISAR ATUALIZAR DADOS CADASTRAIS OU DE REMUNERACAO DO FUNCIONARIO.',
    CAMPOS_OBRIGATORIOS = 'NOME DO PERFIL, STATUS, E PELO MENOS UMA TELA COM PERMISSAO PODE ACESSAR PARA QUE O PERFIL TENHA UTILIDADE NA OPERACAO.',
    CAMPOS_OPCIONAIS = 'DESCRICAO DO PERFIL E AJUSTES FINOS DE PERMISSAO (APENAS CONSULTA OU COM EDICAO).',
    REFLEXOS_PROCESSO = 'AS PERMISSOES DEFINIDAS NESTA TELA CONTROLAM O QUE CADA FUNCIONARIO PODERA EXECUTAR NO SISTEMA, DE ACORDO COM O PERFIL VINCULADO AO SEU CADASTRO.\nUM FUNCIONARIO COM PERFIL QUE POSSUI APENAS PODE CONSULTAR EM UMA TELA CONSEGUE VISUALIZAR OS DADOS, MAS NAO CONSEGUE EDITAR.\nJA UM FUNCIONARIO COM PERFIL QUE POSSUI PODE EDITAR TERA ACESSO COMPLETO DE EDICAO (DENTRO DAS REGRAS DEFINIDAS PARA A TELA).\nESSA CONFIGURACAO SERA A BASE PARA O CONTROLE DE SEGURANCA QUANDO O LOGIN DE USUARIO FOR IMPLANTADO.',
    ERROS_COMUNS = 'CRIAR UM PERFIL E ESQUECER DE MARCAR AS TELAS EM PODE ACESSAR, IMPEDINDO O USO DO PERFIL NA PRATICA.\n\nMARCAR PODE EDITAR PARA TELAS EM QUE O PERFIL DEVERIA TER APENAS CONSULTA.\n\nAJUSTAR PERMISSOES DE TELA E ESQUECER DE CLICAR EM SALVAR ACESSOS DO PERFIL.\n\nVINCULAR FUNCIONARIO A UM PERFIL INCORRETO, LIBERANDO ACESSO OU EDICAO INDEVIDA EM ALGUMA AREA DO SISTEMA.',
    ATIVA = 1,
    DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM TELA)
  AND EXISTS (SELECT 1 FROM TELA);
