WITH TELA AS (
  SELECT ID_TELA
    FROM CORE_TELA
   WHERE CODIGO_TELA = 'CAD005_RH_FUNCIONARIO'
)
UPDATE CORE_AJUDA_TELA
   SET DESCRICAO_PROCESSO = 'TELA RESPONSAVEL PELO CADASTRO GERAL DO FUNCIONARIO, VINCULO AO DEPARTAMENTO, JORNADA E PERFIL DE ACESSO. INCLUI A SECAO DE REMUNERACAO PARA CONTROLAR SALARIO BASE E CARGA HORARIA DE REFERENCIA.',
       PASSO_A_PASSO = '1) INFORMAR OS DADOS BASICOS DO FUNCIONARIO (NOME, CPF, DEPARTAMENTO, JORNADA E PERFIL QUANDO APLICAVEL).\n2) DEFINIR AS DATAS DE ADMISSAO E, SE NECESSARIO, DE DESLIGAMENTO.\n3) PREENCHER A SECAO DE REMUNERACAO COM O TIPO DE SALARIO (MENSALISTA), O SALARIO BASE E A CARGA HORARIA MENSAL DE REFERENCIA.\n4) VERIFICAR SE O FUNCIONARIO ESTA MARCADO COMO ATIVO QUANDO NAO HOUVER DATA DE DESLIGAMENTO.\n5) CLICAR EM SALVAR PARA GRAVAR O REGISTRO OU CANCELAR PARA LIMPAR O FORMULARIO.',
       REFLEXOS_PROCESSO = 'OS DADOS DE REMUNERACAO SERAO UTILIZADOS EM RELATORIOS DE PONTO E FUTUROS CALCULOS DE HORAS EXTRAS.',
       DATA_ATUALIZACAO = datetime(''now'')
 WHERE ID_TELA = (SELECT ID_TELA FROM TELA)
   AND EXISTS (SELECT 1 FROM TELA);
