CREATE TABLE IF NOT EXISTS RH_PONTO_LANCAMENTO (
  ID_PONTO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EMPRESA INTEGER NOT NULL REFERENCES EMP_EMPRESA(ID_EMPRESA) ON DELETE CASCADE,
  ID_FUNCIONARIO TEXT NOT NULL REFERENCES RH_FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE,
  DATA_REFERENCIA DATE NOT NULL,
  ENTRADA_MANHA TEXT,
  SAIDA_MANHA TEXT,
  ENTRADA_TARDE TEXT,
  SAIDA_TARDE TEXT,
  ENTRADA_EXTRA TEXT,
  SAIDA_EXTRA TEXT,
  STATUS_DIA TEXT NOT NULL DEFAULT 'NORMAL',
  OBSERVACAO TEXT,
  USER_LANCAMENTO TEXT,
  DATA_LANCAMENTO DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (ID_EMPRESA, ID_FUNCIONARIO, DATA_REFERENCIA)
);

CREATE INDEX IF NOT EXISTS IDX_RH_PONTO_LANC_FUNC_DATA
  ON RH_PONTO_LANCAMENTO (ID_FUNCIONARIO, DATA_REFERENCIA);
