INSERT OR REPLACE INTO CORE_TELA (
  ID_TELA,
  CODIGO_TELA,
  NOME_TELA,
  MODULO,
  CAMINHO_ROTA,
  ICONE,
  DESCRICAO_TELA,
  ATIVA,
  DATA_CADASTRO,
  DATA_ATUALIZACAO
)
VALUES (
  COALESCE(
    (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'CAD007_RH_PONTO'),
    (SELECT COALESCE(MAX(ID_TELA), 0) + 1 FROM CORE_TELA)
  ),
  'CAD007_RH_PONTO',
  'LANCAMENTO DE PONTO',
  'RH',
  '/rh/ponto',
  'calendar-time',
  'REGISTRO MANUAL DOS HORARIOS DE PONTO DOS FUNCIONARIOS',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_TELA WHERE CODIGO_TELA = 'CAD007_RH_PONTO'), datetime('now')),
  (SELECT DATA_ATUALIZACAO FROM CORE_TELA WHERE CODIGO_TELA = 'CAD007_RH_PONTO')
);
