INSERT INTO SEG_PERFIL_TELA (ID_PERFIL, ID_TELA, PODE_ACESSAR, PODE_CONSULTAR, PODE_EDITAR)
SELECT P.ID_PERFIL,
       T.ID_TELA,
       1, 1, 1
  FROM SEG_PERFIL P
  JOIN CORE_TELA T ON T.CODIGO_TELA = 'CAD007_RH_PONTO'
 WHERE P.ID_PERFIL = 'PER-001'
   AND NOT EXISTS (
     SELECT 1 FROM SEG_PERFIL_TELA SPT
      WHERE SPT.ID_PERFIL = P.ID_PERFIL
        AND SPT.ID_TELA   = T.ID_TELA
   );
