INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA,
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  ATIVA,
  DATA_CADASTRO,
  DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'REALIZAR O LANCAMENTO MANUAL DOS HORARIOS DE TRABALHO (PONTO) DOS FUNCIONARIOS.',
  'UTILIZAR DIARIAMENTE OU PERIODICAMENTE PARA REGISTRAR AS MARCACOES DE ENTRADA E SAIDA, COM BASE NA JORNADA DE TRABALHO DO FUNCIONARIO.',
  'TELA RESPONSAVEL PELO REGISTRO DOS HORARIOS DE PONTO. PERMITE CARREGAR UMA COMPETENCIA (MES/ANO), APLICAR A JORNADA PADRAO NOS DIAS UTEIS E AJUSTAR MANUALMENTE AS HORAS TRABALHADAS. OS LANCAMENTOS SERAO UTILIZADOS PARA EMISSAO DO CARTAO PONTO E CALCULO DE HORAS EXTRAS.',
  '1) SELECIONAR A EMPRESA NA TELA INICIAL.\n2) ACESSAR O MENU RH > LANCAMENTO DE PONTO.\n3) INFORMAR O FUNCIONARIO E A COMPETENCIA (MES/ANO).\n4) CLICAR EM CARREGAR PONTO PARA GERAR A GRADE DE DIAS.\n5) OPCIONAL: UTILIZAR O BOTAO APLICAR JORNADA PARA PREENCHER AUTOMATICAMENTE OS HORARIOS DOS DIAS UTEIS.\n6) AJUSTAR OS HORARIOS DE ENTRADA E SAIDA CONFORME O CARTAO PONTO FISICO.\n7) CLICAR EM SALVAR PONTO PARA GRAVAR OS DADOS.\n8) UTILIZAR OS RELATORIOS (FUTURAMENTE) PARA IMPRESSAO DO CARTAO PONTO E CALCULO DE HORAS EXTRAS.',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD007_RH_PONTO';
