WITH TELA AS (
  SELECT ID_TELA
  FROM CORE_TELA
  WHERE CODIGO_TELA = 'CAD007_RH_PONTO'
)
UPDATE CORE_AJUDA_TELA
SET OBJETIVO_TELA = 'REGISTRAR OS HORARIOS TRABALHADOS PELOS FUNCIONARIOS, PERMITINDO CONTROLE DAS MARCACOES DIARIAS E IDENTIFICACAO DE HORAS NORMAIS E HORAS EXTRAS.',
    QUANDO_UTILIZAR = 'UTILIZAR DIARIAMENTE OU PERIODICAMENTE PARA REGISTRAR AS MARCACOES DE ENTRADA, SAIDA E INTERVALOS DOS FUNCIONARIOS, CONFORME A JORNADA DE TRABALHO DEFINIDA PARA CADA UM.',
    DESCRICAO_PROCESSO = 'TELA UTILIZADA PARA LANCARE OS HORARIOS EFETIVOS TRABALHADOS PELOS FUNCIONARIOS EM DETERMINADA DATA. OS HORARIOS SAO CONFRONTADOS COM A JORNADA PADRAO DO FUNCIONARIO PARA IDENTIFICAR DIFERENCAS, ATRASOS, SAIDAS ANTECIPADAS E HORAS EXTRAS. O INTERVALO OPCIONAL DE 15 MINUTOS NA TARDE PODE SER REGISTRADO QUANDO OCORRER, SEM CARACTER OBRIGATORIO.',
    PASSO_A_PASSO = '1) SELECIONAR O FUNCIONARIO E A DATA DO LANCAMENTO DE PONTO.\n2) CONFERIR A JORNADA DE TRABALHO PREVISTA PARA O FUNCIONARIO.\n3) INFORMAR OS HORARIOS EFETIVOS DE ENTRADA, INTERVALOS E SAIDA.\n4) QUANDO A SAIDA EFETIVA FOR MAIOR QUE A SAIDA PREVISTA NA JORNADA, A DIFERENCA SERA CONSIDERADA COMO HORA EXTRA (PARA RELATORIOS FUTUROS).\n5) SALVAR O LANCAMENTO PARA QUE OS DADOS FIQUEM DISPONIVEIS EM RELATORIOS E NA APURACAO DE HORAS.',
    CAMPOS_OBRIGATORIOS = 'FUNCIONARIO, DATA DO PONTO E PELO MENOS UM HORARIO EFETIVO VINCULADO A JORNADA (ENTRADA E SAIDA PRINCIPAIS).',
    CAMPOS_OPCIONAIS = 'INTERVALOS ADICIONAIS (INCLUINDO INTERVALO OPCIONAL DE 15 MINUTOS NA TARDE, QUANDO REALIZADO), OBSERVACOES E AJUSTES PONTUAIS DE HORARIO.',
    REFLEXOS_PROCESSO = 'OS DADOS LANCADOS NESTA TELA SERAO UTILIZADOS PARA EMISSAO DO CARTAO PONTO, ANALISE DE FREQUENCIA, CALCULO DE HORAS EXTRAS E APOIO AO PROCESSO DE FOLHA DE PAGAMENTO.',
    ERROS_COMUNS = 'NAO CONFERIR SE A EMPRESA E O FUNCIONARIO ESTAO CORRETOS ANTES DO LANCAMENTO.\nINFORMAR HORARIOS EM FORMATO INCORRETO.\nESQUECER DE REGISTRAR A SAIDA OU INTERVALOS UTILIZADOS.\nNAO SALVAR O LANCAMENTO APOS AJUSTES.',
    ATIVA = 1,
    DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM TELA)
  AND EXISTS (SELECT 1 FROM TELA);
