WITH TELA AS (
  SELECT ID_TELA
  FROM CORE_TELA
  WHERE CODIGO_TELA = 'CAD005_RH_FUNCIONARIO'
)
UPDATE CORE_TELA
SET MODULO = 'EMPRESA',
    DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM TELA)
  AND EXISTS (SELECT 1 FROM TELA);
