-- 037_CORE_TELA_RENAME_LAN001.sql

BEGIN TRANSACTION;

-- Renomeia o código da tela de ponto em CORE_TELA
UPDATE CORE_TELA
SET CODIGO_TELA = 'LAN001_RH_PONTO'
WHERE CODIGO_TELA = 'CAD007_RH_PONTO';

-- Atualiza também o código de tela na tabela de ajuda
UPDATE CORE_AJUDA_TELA
SET CODIGO_TELA = 'LAN001_RH_PONTO'
WHERE CODIGO_TELA = 'CAD007_RH_PONTO';

COMMIT;
