-- 037_CORE_TELA_RENAME_LAN001.sql

BEGIN TRANSACTION;

-- 1) Se NÃO existir LAN001_RH_PONTO, simplesmente renomeia CAD007_RH_PONTO para LAN001_RH_PONTO (caminho "limpo")
UPDATE CORE_TELA
SET CODIGO_TELA = 'LAN001_RH_PONTO'
WHERE CODIGO_TELA = 'CAD007_RH_PONTO'
  AND NOT EXISTS (
    SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'LAN001_RH_PONTO'
  );

-- 2) Se EXISTIREM os dois (CAD007 e LAN001), vamos:
--    2.1) Jogar as permissões de SEG_PERFIL_TELA que apontam para CAD007 para LAN001
UPDATE SEG_PERFIL_TELA
SET ID_TELA = (
    SELECT ID_TELA FROM CORE_TELA
    WHERE CODIGO_TELA = 'LAN001_RH_PONTO'
    LIMIT 1
)
WHERE ID_TELA = (
    SELECT ID_TELA FROM CORE_TELA
    WHERE CODIGO_TELA = 'CAD007_RH_PONTO'
    LIMIT 1
)
  AND EXISTS (SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'LAN001_RH_PONTO')
  AND EXISTS (SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'CAD007_RH_PONTO');

--    2.2) Remover o registro antigo CAD007_RH_PONTO se LAN001 já existe
DELETE FROM CORE_TELA
WHERE CODIGO_TELA = 'CAD007_RH_PONTO'
  AND EXISTS (SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'LAN001_RH_PONTO');

-- 3) Garantir que a ajuda sempre enxergue LAN001_RH_PONTO
UPDATE CORE_AJUDA_TELA
SET CODIGO_TELA = 'LAN001_RH_PONTO'
WHERE CODIGO_TELA IN ('CAD007_RH_PONTO', 'LAN001_RH_PONTO');

COMMIT;
