UPDATE CORE_TELA
   SET CODIGO_TELA = 'LAN001_RH_PONTO'
 WHERE CODIGO_TELA = 'CAD007_RH_PONTO';

UPDATE CORE_AJUDA_TELA
   SET CODIGO_TELA = 'LAN001_RH_PONTO'
 WHERE CODIGO_TELA = 'CAD007_RH_PONTO';

UPDATE SEG_PERFIL_TELA
   SET CODIGO_TELA = 'LAN001_RH_PONTO'
 WHERE CODIGO_TELA = 'CAD007_RH_PONTO';
