-- Renomeia colunas para seguir o padrão de períodos
ALTER TABLE RH_JORNADA_TRABALHO RENAME COLUMN HORA_ENTRADA1 TO HORA_ENTRADA_MANHA;
ALTER TABLE RH_JORNADA_TRABALHO RENAME COLUMN HORA_SAIDA1 TO HORA_SAIDA_MANHA;
ALTER TABLE RH_JORNADA_TRABALHO RENAME COLUMN HORA_ENTRADA2 TO HORA_ENTRADA_TARDE;
ALTER TABLE RH_JORNADA_TRABALHO RENAME COLUMN HORA_SAIDA2 TO HORA_SAIDA_TARDE;
ALTER TABLE RH_JORNADA_TRABALHO RENAME COLUMN HORA_ENTRADA3 TO HORA_ENTRADA_INTERVALO;
ALTER TABLE RH_JORNADA_TRABALHO RENAME COLUMN HORA_SAIDA3 TO HORA_SAIDA_INTERVALO;

-- Campo de tolerância em minutos para cálculo de ponto
ALTER TABLE RH_JORNADA_TRABALHO ADD COLUMN TOLERANCIA_MINUTOS INTEGER NOT NULL DEFAULT 0;
