-- 038_RH_FUNCIONARIO_SALARIO.sql

-- Cria tabela de histórico de salários
CREATE TABLE IF NOT EXISTS RH_FUNCIONARIO_SALARIO (
  ID_SALARIO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_FUNCIONARIO TEXT NOT NULL REFERENCES RH_FUNCIONARIO(ID_FUNCIONARIO),
  DATA_INICIO_VIGENCIA DATE NOT NULL,
  DATA_FIM_VIGENCIA DATE NULL,
  TIPO_SALARIO TEXT NOT NULL DEFAULT 'MENSAL',
  VALOR NUMERIC(12,2) NOT NULL,
  OBSERVACAO TEXT NULL,
  CREATED_AT TEXT NOT NULL DEFAULT (datetime('now')),
  UPDATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Popula histórico inicial a partir do salário base atual, quando existir
INSERT INTO RH_FUNCIONARIO_SALARIO (
  ID_FUNCIONARIO,
  DATA_INICIO_VIGENCIA,
  DATA_FIM_VIGENCIA,
  TIPO_SALARIO,
  VALOR
)
SELECT
  ID_FUNCIONARIO,
  date('now') AS DATA_INICIO_VIGENCIA,
  NULL AS DATA_FIM_VIGENCIA,
  'MENSAL' AS TIPO_SALARIO,
  SALARIO_BASE AS VALOR
FROM RH_FUNCIONARIO
WHERE SALARIO_BASE IS NOT NULL
  AND SALARIO_BASE <> 0
  AND NOT EXISTS (
    SELECT 1
    FROM RH_FUNCIONARIO_SALARIO s
    WHERE s.ID_FUNCIONARIO = RH_FUNCIONARIO.ID_FUNCIONARIO
      AND s.DATA_FIM_VIGENCIA IS NULL
  );
