CREATE TABLE IF NOT EXISTS RH_FUNCIONARIO_SALARIO (
  ID_SALARIO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_FUNCIONARIO INTEGER NOT NULL REFERENCES RH_FUNCIONARIO(ID_FUNCIONARIO),
  DATA_INICIO_VIGENCIA DATE NOT NULL,
  DATA_FIM_VIGENCIA DATE NULL,
  TIPO_SALARIO TEXT NOT NULL DEFAULT 'MENSAL',
  VALOR NUMERIC(12,2) NOT NULL,
  OBSERVACAO TEXT NULL,
  CREATED_AT TEXT NOT NULL DEFAULT (datetime('now')),
  UPDATED_AT TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO RH_FUNCIONARIO_SALARIO (
  ID_FUNCIONARIO,
  DATA_INICIO_VIGENCIA,
  DATA_FIM_VIGENCIA,
  TIPO_SALARIO,
  VALOR,
  OBSERVACAO
)
SELECT
  ID_FUNCIONARIO,
  date('now') AS DATA_INICIO_VIGENCIA,
  NULL AS DATA_FIM_VIGENCIA,
  COALESCE(TIPO_SALARIO, 'MENSAL') AS TIPO_SALARIO,
  COALESCE(SALARIO_BASE, 0) AS VALOR,
  NULL AS OBSERVACAO
FROM RH_FUNCIONARIO
WHERE COALESCE(SALARIO_BASE, 0) > 0
  AND NOT EXISTS (
    SELECT 1 FROM RH_FUNCIONARIO_SALARIO s
    WHERE s.ID_FUNCIONARIO = RH_FUNCIONARIO.ID_FUNCIONARIO
  );
