-- Renomeia colunas antigas de horário na tabela RH_JORNADA_TRABALHO
ALTER TABLE RH_JORNADA_TRABALHO RENAME COLUMN HORA_ENTRADA_1 TO HORA_ENTRADA_MANHA;
ALTER TABLE RH_JORNADA_TRABALHO RENAME COLUMN HORA_SAIDA_1   TO HORA_SAIDA_MANHA;
ALTER TABLE RH_JORNADA_TRABALHO RENAME COLUMN HORA_ENTRADA_2 TO HORA_ENTRADA_TARDE;
ALTER TABLE RH_JORNADA_TRABALHO RENAME COLUMN HORA_SAIDA_2   TO HORA_SAIDA_TARDE;
ALTER TABLE RH_JORNADA_TRABALHO RENAME COLUMN HORA_ENTRADA_3 TO HORA_ENTRADA_INTERVALO;
ALTER TABLE RH_JORNADA_TRABALHO RENAME COLUMN HORA_SAIDA_3   TO HORA_SAIDA_INTERVALO;
