ALTER TABLE RH_PONTO_LANCAMENTO ADD COLUMN TIPO_OCORRENCIA TEXT NOT NULL DEFAULT 'NORMAL';
ALTER TABLE RH_PONTO_LANCAMENTO ADD COLUMN ID_MOTIVO_FALTA INTEGER NULL REFERENCES RH_FALTA_JUSTIFICATIVA_MOTIVO(ID_MOTIVO);
ALTER TABLE RH_PONTO_LANCAMENTO ADD COLUMN OBS_FALTA TEXT NULL;
ALTER TABLE RH_PONTO_LANCAMENTO ADD COLUMN TEMPO_TRABALHADO_MINUTOS INTEGER NOT NULL DEFAULT 0;
ALTER TABLE RH_PONTO_LANCAMENTO ADD COLUMN HORAS_EXTRAS_MINUTOS INTEGER NOT NULL DEFAULT 0;
