-- 041_CORE_AJUDA_REMOVE_CAD007.sql
-- Migration intencionalmente vazia.
-- A limpeza de referências à tela CAD007_RH_PONTO já foi feita manualmente no banco.
-- Esta migration existe apenas para manter a sequência de versões alinhada.
