-- Adiciona campos para controle de faltas e ocorrências diárias no ponto
ALTER TABLE RH_PONTO_LANCAMENTO ADD COLUMN TIPO_OCORRENCIA TEXT NOT NULL DEFAULT 'NORMAL';
ALTER TABLE RH_PONTO_LANCAMENTO ADD COLUMN ID_MOTIVO_FALTA INTEGER NULL;
ALTER TABLE RH_PONTO_LANCAMENTO ADD COLUMN OBS_FALTA TEXT NULL;
