-- Cria tabela de motivos para faltas justificadas
CREATE TABLE IF NOT EXISTS RH_FALTA_JUSTIFICATIVA_MOTIVO (
  ID_MOTIVO INTEGER PRIMARY KEY AUTOINCREMENT,
  DESCRICAO TEXT NOT NULL,
  ATIVO INTEGER NOT NULL DEFAULT 1,
  ORDEM_EXIBICAO INTEGER NOT NULL DEFAULT 0
);

INSERT INTO RH_FALTA_JUSTIFICATIVA_MOTIVO (DESCRICAO) VALUES
  ('ATESTADO MEDICO'),
  ('COMPENSACAO DE BANCO DE HORAS'),
  ('ATIVIDADE EXTERNA AUTORIZADA'),
  ('FERIAS'),
  ('LICENCA'),
  ('OUTROS');
