-- 044_CORE_TELA_ALINHAMENTOS_SEG_RH.sql
-- Migration intencionalmente vazia.
-- Os alinhamentos de telas e módulos de SEG/RH já foram ajustados
-- nas migrations anteriores e/ou diretamente no banco.
-- Esta migration existe apenas para manter a sequência de versões.
