-- Alinha códigos e módulos das telas de segurança e ponto
UPDATE CORE_TELA
   SET CODIGO_TELA = 'LAN001_RH_PONTO',
       CAMINHO_ROTA = '/rh/ponto',
       MODULO = 'RH'
 WHERE CODIGO_TELA = 'CAD007_RH_PONTO';

UPDATE CORE_AJUDA_TELA
   SET CODIGO_TELA = 'LAN001_RH_PONTO'
 WHERE CODIGO_TELA = 'CAD007_RH_PONTO';

UPDATE CORE_TELA
   SET MODULO = 'EMPRESA'
 WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL';
