-- 045_RH_FALTA_JUSTIFICATIVA_MOTIVO_NORMALIZAR.sql

BEGIN TRANSACTION;

-- Padronizar descrições em caixa alta sem acento
UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET DESCRICAO = 'ATESTADO MEDICO'
WHERE ID_MOTIVO = 1;

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET DESCRICAO = 'COMPENSACAO DE BANCO DE HORAS'
WHERE ID_MOTIVO = 2;

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET DESCRICAO = 'ATIVIDADE EXTERNA AUTORIZADA'
WHERE ID_MOTIVO = 3;

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET DESCRICAO = 'FERIAS'
WHERE ID_MOTIVO = 4;

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET DESCRICAO = 'OUTROS'
WHERE ID_MOTIVO = 5;

-- Novo motivo LICENCA
INSERT INTO RH_FALTA_JUSTIFICATIVA_MOTIVO (DESCRICAO, ATIVO, ORDEM_EXIBICAO)
VALUES ('LICENCA', 1, 5);

-- Normalizar ordem de exibicao
UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 1
WHERE DESCRICAO = 'ATESTADO MEDICO';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 2
WHERE DESCRICAO = 'COMPENSACAO DE BANCO DE HORAS';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 3
WHERE DESCRICAO = 'ATIVIDADE EXTERNA AUTORIZADA';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 4
WHERE DESCRICAO = 'FERIAS';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 6
WHERE DESCRICAO = 'OUTROS';

COMMIT;
