-- 045_RH_FALTA_JUSTIFICATIVA_MOTIVO_NORMALIZAR.sql

-- Remove motivos duplicados de LICENCA, mantendo apenas o menor ID
DELETE FROM RH_FALTA_JUSTIFICATIVA_MOTIVO
WHERE DESCRICAO = 'LICENCA'
  AND ID_MOTIVO NOT IN (
    SELECT MIN(ID_MOTIVO)
    FROM RH_FALTA_JUSTIFICATIVA_MOTIVO
    WHERE DESCRICAO = 'LICENCA'
  );

-- Ajusta a ordem de exibicao de cada motivo, conforme padrao definido

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 1
WHERE DESCRICAO = 'ATESTADO MEDICO';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 2
WHERE DESCRICAO LIKE 'COMPENSACAO DE BANCO%';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 3
WHERE DESCRICAO = 'ATIVIDADE EXTERNA AUTORIZADA';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 4
WHERE DESCRICAO = 'FERIAS';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 5
WHERE DESCRICAO = 'LICENCA';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 99
WHERE DESCRICAO = 'OUTROS';
