-- 045_RH_FALTA_JUSTIFICATIVA_MOTIVO_PADRONIZAR.sql

BEGIN TRANSACTION;

-- 1) Padronizar textos existentes em CAIXA ALTA sem acento

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET DESCRICAO = 'ATESTADO MEDICO'
WHERE ID_MOTIVO = 1;

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET DESCRICAO = 'COMPENSACAO DE BANCO DE HORAS'
WHERE ID_MOTIVO = 2;

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET DESCRICAO = 'ATIVIDADE EXTERNA AUTORIZADA'
WHERE ID_MOTIVO = 3;

-- 2) Quebrar FÉRIAS / LICENÇA em dois registros separados

-- ID 4 vira apenas FERIAS
UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET DESCRICAO = 'FERIAS'
WHERE ID_MOTIVO = 4;

-- Criar novo registro para LICENCA
INSERT INTO RH_FALTA_JUSTIFICATIVA_MOTIVO (DESCRICAO)
VALUES ('LICENCA');

-- 3) Padronizar OUTROS

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET DESCRICAO = 'OUTROS'
WHERE ID_MOTIVO = 5;

COMMIT;
