-- 047_CORE_TELA_CLEANUP_PONTO_v2.sql

BEGIN TRANSACTION;

-- 1) Se JÁ existir LAN001_RH_PONTO e AINDA existir CAD007_RH_PONTO:
--    - repontar permissões de CAD007 -> LAN001
--    - remover CAD007 da CORE_TELA

UPDATE SEG_PERFIL_TELA
SET ID_TELA = (
  SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'LAN001_RH_PONTO'
)
WHERE ID_TELA = (
  SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'CAD007_RH_PONTO'
)
AND EXISTS (SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'LAN001_RH_PONTO')
AND EXISTS (SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'CAD007_RH_PONTO');

DELETE FROM CORE_TELA
WHERE CODIGO_TELA = 'CAD007_RH_PONTO'
  AND EXISTS (SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'LAN001_RH_PONTO');

-- 2) Se NÃO existir LAN001_RH_PONTO mas existir CAD007_RH_PONTO:
--    - renomear CAD007_RH_PONTO para LAN001_RH_PONTO (mantém o mesmo ID_TELA)

UPDATE CORE_TELA
SET CODIGO_TELA = 'LAN001_RH_PONTO'
WHERE CODIGO_TELA = 'CAD007_RH_PONTO'
  AND NOT EXISTS (SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'LAN001_RH_PONTO');

-- 3) Remover ajuda vinculada à CAD007_RH_PONTO (caso ainda exista)

DELETE FROM CORE_AJUDA_TELA
WHERE CODIGO_TELA = 'CAD007_RH_PONTO';

-- 4) Garantir que CAD006_SEG_PERFIL esteja no módulo EMPRESA

UPDATE CORE_TELA
SET MODULO = 'EMPRESA'
WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL';

COMMIT;
