-- 047_CORE_TELA_CLEANUP_PONTO_v2.sql

BEGIN TRANSACTION;

-- 1) Garantir que exista a tela LAN001_RH_PONTO em CORE_TELA
--    a partir da CAD007_RH_PONTO, se necessário

-- Se LAN001 ainda não existe e CAD007 existe, criar LAN001 copiando de CAD007
INSERT INTO CORE_TELA (CODIGO_TELA, DESCRICAO, MODULO, CAMINHO_ROTA)
SELECT 'LAN001_RH_PONTO', DESCRICAO, MODULO, CAMINHO_ROTA
FROM CORE_TELA
WHERE CODIGO_TELA = 'CAD007_RH_PONTO'
  AND NOT EXISTS (
    SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'LAN001_RH_PONTO'
  );

-- 2) Se existirem permissões vinculadas à CAD007, migrar para LAN001
UPDATE SEG_PERFIL_TELA
SET ID_TELA = (
  SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'LAN001_RH_PONTO'
)
WHERE ID_TELA = (
  SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'CAD007_RH_PONTO'
)
AND EXISTS (
  SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'LAN001_RH_PONTO'
)
AND EXISTS (
  SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'CAD007_RH_PONTO'
);

-- 3) Remover CAD007_RH_PONTO de CORE_TELA, mantendo apenas LAN001_RH_PONTO
DELETE FROM CORE_TELA
WHERE CODIGO_TELA = 'CAD007_RH_PONTO'
  AND EXISTS (
    SELECT 1 FROM CORE_TELA WHERE CODIGO_TELA = 'LAN001_RH_PONTO'
  );

-- 4) Remover entradas de ajuda vinculadas à CAD007_RH_PONTO
DELETE FROM CORE_AJUDA_TELA
WHERE CODIGO_TELA = 'CAD007_RH_PONTO';

-- 5) Garantir que a tela CAD006_SEG_PERFIL esteja sob o módulo EMPRESA
UPDATE CORE_TELA
SET MODULO = 'EMPRESA'
WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL';

COMMIT;
