-- 049_RH_FALTA_JUSTIFICATIVA_MOTIVO_CLEANUP.sql
-- Migração convertida em NO-OP para evitar execuções no ambiente atual.
-- Intencionalmente sem comandos SQL (sem BEGIN, COMMIT ou qualquer DML/DDL).
