-- 049_RH_FALTA_JUSTIFICATIVA_MOTIVO_CLEANUP.sql

BEGIN TRANSACTION;

-- 1) Manter apenas um registro de LICENCA
DELETE FROM RH_FALTA_JUSTIFICATIVA_MOTIVO
WHERE DESCRICAO = 'LICENCA'
  AND ID_MOTIVO NOT IN (
    SELECT MIN(ID_MOTIVO)
    FROM RH_FALTA_JUSTIFICATIVA_MOTIVO
    WHERE DESCRICAO = 'LICENCA'
  );

-- 2) Padronizar ORDEM_EXIBICAO das descricoes canônicas
UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 10
WHERE DESCRICAO = 'ATESTADO MEDICO';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 20
WHERE DESCRICAO = 'COMPENSACAO BANCO DE HORAS';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 30
WHERE DESCRICAO = 'ATIVIDADE EXTERNA AUTORIZADA';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 40
WHERE DESCRICAO = 'FERIAS';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 50
WHERE DESCRICAO = 'LICENCA';

UPDATE RH_FALTA_JUSTIFICATIVA_MOTIVO
SET ORDEM_EXIBICAO = 60
WHERE DESCRICAO = 'OUTROS';

COMMIT;
