CREATE TABLE IF NOT EXISTS RH_BANCO_HORAS_AJUSTE (
  ID_AJUSTE INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EMPRESA INTEGER NOT NULL REFERENCES EMP_EMPRESA(ID_EMPRESA) ON DELETE CASCADE,
  ID_FUNCIONARIO TEXT NOT NULL REFERENCES RH_FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE,
  COMPETENCIA CHAR(7) NOT NULL,
  MINUTOS INTEGER NOT NULL,
  TIPO_AJUSTE CHAR(20) NOT NULL,
  OBSERVACAO VARCHAR(255),
  DATA_CRIACAO TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS IDX_RH_BANCO_HORAS_AJUSTE_COMPETENCIA
  ON RH_BANCO_HORAS_AJUSTE (COMPETENCIA, ID_FUNCIONARIO);
