CREATE TABLE IF NOT EXISTS RH_BANCO_HORAS_FECHAMENTO (
  ID_FECHAMENTO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EMPRESA INTEGER NOT NULL REFERENCES EMP_EMPRESA(ID_EMPRESA) ON DELETE CASCADE,
  ID_FUNCIONARIO TEXT NOT NULL REFERENCES RH_FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE,
  ANO INTEGER NOT NULL,
  MES INTEGER NOT NULL,
  COMPETENCIA CHAR(7) NOT NULL,
  SALDO_ANTERIOR_MINUTOS INTEGER NOT NULL DEFAULT 0,
  HORAS_EXTRAS_50_MINUTOS INTEGER NOT NULL DEFAULT 0,
  HORAS_EXTRAS_100_MINUTOS INTEGER NOT NULL DEFAULT 0,
  HORAS_DEVIDAS_MINUTOS INTEGER NOT NULL DEFAULT 0,
  AJUSTES_MINUTOS INTEGER NOT NULL DEFAULT 0,
  SALDO_FINAL_MINUTOS INTEGER NOT NULL DEFAULT 0,
  POLITICA_FALTAS CHAR(20) NOT NULL,
  ZEROU_BANCO CHAR(1) NOT NULL DEFAULT 'N',
  VALOR_PAGAR DECIMAL(10,2),
  VALOR_DESCONTAR DECIMAL(10,2),
  DATA_FECHAMENTO TEXT NOT NULL DEFAULT (datetime('now')),
  USUARIO_FECHAMENTO TEXT,
  CONSTRAINT UQ_RH_BANCO_HORAS_FECHAMENTO UNIQUE (ID_EMPRESA, ID_FUNCIONARIO, ANO, MES)
);

CREATE INDEX IF NOT EXISTS IDX_RH_BANCO_HORAS_FECHAMENTO_COMPETENCIA
  ON RH_BANCO_HORAS_FECHAMENTO (ID_EMPRESA, COMPETENCIA);

CREATE INDEX IF NOT EXISTS IDX_RH_BANCO_HORAS_FECHAMENTO_FUNC
  ON RH_BANCO_HORAS_FECHAMENTO (ID_FUNCIONARIO, ANO, MES);
