-- Adiciona helps para telas de Banco de Horas

-- Help para REL001_RH_BANCO_HORAS
INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA,
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA,
  DATA_CADASTRO,
  DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'CALCULAR E GERENCIAR O BANCO DE HORAS DOS FUNCIONARIOS.',
  'UTILIZAR AO FECHAR UMA COMPETENCIA MENSAL OU QUANDO PRECISAR AJUSTAR O SALDO DE HORAS.',
  'TELA RESPONSAVEL PELO CALCULO DO BANCO DE HORAS, CONSIDERANDO HORAS EXTRAS (50% E 100%), HORAS DEVIDAS, AJUSTES MANUAIS E POLITICA DE FALTAS.',
  '1) INFORMAR O FUNCIONARIO E A COMPETENCIA (MES/ANO).\n2) CLICAR EM CALCULAR PARA PROCESSAR OS REGISTROS DE PONTO.\n3) AVALIAR O RESUMO DO MES (SALDO ANTERIOR, HORAS EXTRAS, HORAS DEVEDORAS E AJUSTES).\n4) DEFINIR A POLITICA DE FALTAS E SE O BANCO DEVE SER ZERADO.\n5) REGISTRAR AJUSTES MANUAIS QUANDO NECESSARIO (CREDITO OU DEBITO NO FORMATO HH:MM).\n6) SALVAR PARA ATUALIZAR O HISTORICO DE MOVIMENTACOES.',
  'FUNCIONARIO, COMPETENCIA (MES/ANO).',
  'POLITICA DE FALTAS, DECISAO DE ZERAR O BANCO, AJUSTES MANUAIS COM DATA E OBSERVACAO.',
  'O CALCULO ATUALIZA O SALDO DE HORAS E OS VALORES A PAGAR OU DESCONTAR, REGISTRANDO MOVIMENTACOES PARA CONSULTAS FUTURAS.',
  'NAO INFORMAR FUNCIONARIO OU COMPETENCIA, INFORMAR HORAS EM FORMATO INVALIDO (HH:MM) OU ESQUECER DE SALVAR APOS OS AJUSTES.',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'REL001_RH_BANCO_HORAS';

-- Help para CONS001_RH_BANCO_HORAS
INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA,
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA,
  DATA_CADASTRO,
  DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'CONSULTAR PERIODOS FECHADOS DE BANCO DE HORAS E GERAR RELATORIOS.',
  'UTILIZAR QUANDO PRECISAR VISUALIZAR HISTORICO DE CALCULOS OU EXPORTAR DADOS PARA CONTABILIDADE.',
  'TELA DE CONSULTA QUE LISTA PERIODOS JA CALCULADOS, PERMITINDO VISUALIZAR RESUMOS E GERAR PDF OU EXCEL.',
  '1) INFORMAR O FUNCIONARIO E A COMPETENCIA PARA CONSULTA.\n2) EXECUTAR A BUSCA PARA LISTAR PERIODOS FECHADOS.\n3) UTILIZAR AS OPCOES DE EXPORTACAO PARA GERAR PDF OU EXCEL CONFORME NECESSARIO.\n4) REVISAR OS ARQUIVOS GERADOS ANTES DE ENVIAR PARA A CONTABILIDADE.',
  'FUNCIONARIO, COMPETENCIA (MES/ANO).',
  'SELECAO MULTIPLA DE FUNCIONARIOS PARA EXPORTACAO EM LOTE.',
  'OS RELATORIOS GERADOS SERVEM PARA ARQUIVO E PARA ENVIO A CONTABILIDADE, GARANTINDO HISTORICO DE PERIODOS FECHADOS.',
  'PESQUISAR SEM INFORMAR COMPETENCIA, NAO FILTRAR O FUNCIONARIO CORRETO OU ESQUECER DE ATUALIZAR OS ARQUIVOS EXPORTADOS.',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CONS001_RH_BANCO_HORAS';
