CREATE TABLE IF NOT EXISTS RH_BANCO_HORAS_PERIODO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EMPRESA INTEGER NOT NULL REFERENCES EMP_EMPRESA(ID_EMPRESA) ON DELETE CASCADE,
  ID_FUNCIONARIO TEXT NOT NULL REFERENCES RH_FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE,
  ANO_REFERENCIA INTEGER NOT NULL,
  MES_REFERENCIA INTEGER NOT NULL,
  SITUACAO_PERIODO VARCHAR(20) NOT NULL DEFAULT 'NAO_INICIADO',
  DATA_ULTIMA_ATUALIZACAO TEXT NOT NULL DEFAULT (datetime('now')),
  ID_USUARIO_ULTIMA_ATUALIZACAO TEXT,
  CREATED_AT TEXT NOT NULL DEFAULT (datetime('now')),
  UPDATED_AT TEXT NOT NULL DEFAULT (datetime('now')),
  CONSTRAINT UQ_RH_BANCO_HORAS_PERIODO UNIQUE (ID_EMPRESA, ID_FUNCIONARIO, ANO_REFERENCIA, MES_REFERENCIA)
);

CREATE INDEX IF NOT EXISTS IDX_RH_BANCO_HORAS_PERIODO_FUNCIONARIO
  ON RH_BANCO_HORAS_PERIODO (ID_FUNCIONARIO, ANO_REFERENCIA, MES_REFERENCIA);
