ALTER TABLE RH_BANCO_HORAS_FECHAMENTO
  ADD COLUMN DATA_LIBERACAO_EDICAO TEXT;

ALTER TABLE RH_BANCO_HORAS_FECHAMENTO
  ADD COLUMN ID_USUARIO_MASTER_LIBERACAO TEXT;

ALTER TABLE RH_BANCO_HORAS_FECHAMENTO
  ADD COLUMN MOTIVO_LIBERACAO TEXT;
