CREATE TABLE IF NOT EXISTS FIN_PLANO_CONTA (
  FIN_PLANO_CONTA_ID INTEGER PRIMARY KEY,
  FIN_PLANO_CONTA_PAI_ID INTEGER NULL,
  FIN_PLANO_CONTA_NATUREZA TEXT NOT NULL CHECK (FIN_PLANO_CONTA_NATUREZA IN ('RECEITA', 'DESPESA')),
  FIN_PLANO_CONTA_NOME TEXT NOT NULL,
  FIN_PLANO_CONTA_CODIGO TEXT NOT NULL UNIQUE,
  FIN_PLANO_CONTA_ATIVO INTEGER NOT NULL DEFAULT 1,
  FIN_PLANO_CONTA_ORDEM INTEGER NOT NULL DEFAULT 0,
  FIN_PLANO_CONTA_VISIVEL_DRE INTEGER NOT NULL DEFAULT 1,
  FIN_PLANO_CONTA_OBRIGA_CENTRO_CUSTO INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (FIN_PLANO_CONTA_PAI_ID) REFERENCES FIN_PLANO_CONTA(FIN_PLANO_CONTA_ID)
);

CREATE INDEX IF NOT EXISTS IDX_FIN_PLANO_CONTA_PAI
  ON FIN_PLANO_CONTA (FIN_PLANO_CONTA_PAI_ID);

CREATE INDEX IF NOT EXISTS IDX_FIN_PLANO_CONTA_ATIVO
  ON FIN_PLANO_CONTA (FIN_PLANO_CONTA_ATIVO);

CREATE TABLE IF NOT EXISTS FIN_CENTRO_CUSTO (
  FIN_CENTRO_CUSTO_ID INTEGER PRIMARY KEY,
  FIN_CENTRO_CUSTO_PAI_ID INTEGER NULL,
  FIN_CENTRO_CUSTO_NOME TEXT NOT NULL,
  FIN_CENTRO_CUSTO_CODIGO TEXT NOT NULL UNIQUE,
  FIN_CENTRO_CUSTO_ATIVO INTEGER NOT NULL DEFAULT 1,
  FIN_CENTRO_CUSTO_ORDEM INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (FIN_CENTRO_CUSTO_PAI_ID) REFERENCES FIN_CENTRO_CUSTO(FIN_CENTRO_CUSTO_ID)
);

CREATE INDEX IF NOT EXISTS IDX_FIN_CENTRO_CUSTO_PAI
  ON FIN_CENTRO_CUSTO (FIN_CENTRO_CUSTO_PAI_ID);

CREATE INDEX IF NOT EXISTS IDX_FIN_CENTRO_CUSTO_ATIVO
  ON FIN_CENTRO_CUSTO (FIN_CENTRO_CUSTO_ATIVO);

CREATE TABLE IF NOT EXISTS FIN_ESTRUTURA_DRE (
  FIN_ESTRUTURA_DRE_ID INTEGER PRIMARY KEY,
  FIN_ESTRUTURA_DRE_PAI_ID INTEGER NULL,
  FIN_ESTRUTURA_DRE_NOME TEXT NOT NULL,
  FIN_ESTRUTURA_DRE_ORDEM INTEGER NOT NULL DEFAULT 0,
  FIN_ESTRUTURA_DRE_NATUREZA TEXT NOT NULL CHECK (FIN_ESTRUTURA_DRE_NATUREZA IN ('RECEITA', 'DESPESA', 'CALCULADO')),
  FIN_ESTRUTURA_DRE_TIPO_GASTO TEXT NOT NULL DEFAULT 'NAO_APLICA' CHECK (FIN_ESTRUTURA_DRE_TIPO_GASTO IN ('FIXO', 'VARIAVEL', 'NAO_APLICA')),
  FIN_ESTRUTURA_DRE_ATIVO INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (FIN_ESTRUTURA_DRE_PAI_ID) REFERENCES FIN_ESTRUTURA_DRE(FIN_ESTRUTURA_DRE_ID)
);

CREATE INDEX IF NOT EXISTS IDX_FIN_ESTRUTURA_DRE_PAI
  ON FIN_ESTRUTURA_DRE (FIN_ESTRUTURA_DRE_PAI_ID);

CREATE INDEX IF NOT EXISTS IDX_FIN_ESTRUTURA_DRE_ATIVO
  ON FIN_ESTRUTURA_DRE (FIN_ESTRUTURA_DRE_ATIVO);

CREATE TABLE IF NOT EXISTS FIN_ESTRUTURA_DRE_CONTA (
  FIN_ESTRUTURA_DRE_CONTA_ID INTEGER PRIMARY KEY,
  FIN_ESTRUTURA_DRE_ID INTEGER NOT NULL,
  FIN_PLANO_CONTA_ID INTEGER NOT NULL,
  FIN_ESTRUTURA_DRE_CONTA_ATIVO INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (FIN_ESTRUTURA_DRE_ID) REFERENCES FIN_ESTRUTURA_DRE(FIN_ESTRUTURA_DRE_ID),
  FOREIGN KEY (FIN_PLANO_CONTA_ID) REFERENCES FIN_PLANO_CONTA(FIN_PLANO_CONTA_ID)
);

CREATE INDEX IF NOT EXISTS IDX_FIN_ESTRUTURA_DRE_CONTA
  ON FIN_ESTRUTURA_DRE_CONTA (FIN_ESTRUTURA_DRE_ID, FIN_PLANO_CONTA_ID);

CREATE TABLE IF NOT EXISTS FIN_LANCAMENTO (
  FIN_LANCAMENTO_ID INTEGER PRIMARY KEY,
  FIN_LANCAMENTO_DATA TEXT NOT NULL,
  FIN_LANCAMENTO_HISTORICO TEXT,
  FIN_LANCAMENTO_VALOR REAL NOT NULL DEFAULT 0,
  FIN_PLANO_CONTA_ID INTEGER NOT NULL,
  FIN_CENTRO_CUSTO_ID INTEGER NULL,
  FIN_LANCAMENTO_DOCUMENTO TEXT,
  FIN_LANCAMENTO_CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  FIN_LANCAMENTO_ATUALIZADO_EM TEXT,
  FOREIGN KEY (FIN_PLANO_CONTA_ID) REFERENCES FIN_PLANO_CONTA(FIN_PLANO_CONTA_ID),
  FOREIGN KEY (FIN_CENTRO_CUSTO_ID) REFERENCES FIN_CENTRO_CUSTO(FIN_CENTRO_CUSTO_ID)
);

CREATE INDEX IF NOT EXISTS IDX_FIN_LANCAMENTO_DATA
  ON FIN_LANCAMENTO (FIN_LANCAMENTO_DATA);

CREATE INDEX IF NOT EXISTS IDX_FIN_LANCAMENTO_PLANO_CONTA
  ON FIN_LANCAMENTO (FIN_PLANO_CONTA_ID);

CREATE INDEX IF NOT EXISTS IDX_FIN_LANCAMENTO_CENTRO_CUSTO
  ON FIN_LANCAMENTO (FIN_CENTRO_CUSTO_ID);
