INSERT OR REPLACE INTO CORE_TELA (
  ID_TELA,
  CODIGO_TELA,
  NOME_TELA,
  MODULO,
  CAMINHO_ROTA,
  ICONE,
  DESCRICAO_TELA,
  ATIVA,
  DATA_CADASTRO,
  DATA_ATUALIZACAO
)
VALUES (
  COALESCE(
    (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN001_PLANO_CONTA'),
    (SELECT COALESCE(MAX(ID_TELA), 0) + 1 FROM CORE_TELA)
  ),
  'FIN001_PLANO_CONTA',
  'PLANO DE CONTAS',
  'FINANCEIRO',
  '/financeiro/plano-conta',
  'hierarchy',
  'CADASTRO E MANUTENCAO DO PLANO DE CONTAS FINANCEIRO',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_TELA WHERE CODIGO_TELA = 'FIN001_PLANO_CONTA'), datetime('now')),
  (SELECT DATA_ATUALIZACAO FROM CORE_TELA WHERE CODIGO_TELA = 'FIN001_PLANO_CONTA')
);

INSERT OR REPLACE INTO CORE_TELA (
  ID_TELA,
  CODIGO_TELA,
  NOME_TELA,
  MODULO,
  CAMINHO_ROTA,
  ICONE,
  DESCRICAO_TELA,
  ATIVA,
  DATA_CADASTRO,
  DATA_ATUALIZACAO
)
VALUES (
  COALESCE(
    (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN002_CENTRO_CUSTO'),
    (SELECT COALESCE(MAX(ID_TELA), 0) + 1 FROM CORE_TELA)
  ),
  'FIN002_CENTRO_CUSTO',
  'CENTRO DE CUSTO',
  'FINANCEIRO',
  '/financeiro/centro-custo',
  'focus',
  'CADASTRO DE CENTROS DE CUSTO COM HIERARQUIA',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_TELA WHERE CODIGO_TELA = 'FIN002_CENTRO_CUSTO'), datetime('now')),
  (SELECT DATA_ATUALIZACAO FROM CORE_TELA WHERE CODIGO_TELA = 'FIN002_CENTRO_CUSTO')
);

INSERT OR REPLACE INTO CORE_TELA (
  ID_TELA,
  CODIGO_TELA,
  NOME_TELA,
  MODULO,
  CAMINHO_ROTA,
  ICONE,
  DESCRICAO_TELA,
  ATIVA,
  DATA_CADASTRO,
  DATA_ATUALIZACAO
)
VALUES (
  COALESCE(
    (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN003_ESTRUTURA_DRE'),
    (SELECT COALESCE(MAX(ID_TELA), 0) + 1 FROM CORE_TELA)
  ),
  'FIN003_ESTRUTURA_DRE',
  'ESTRUTURA DO DRE',
  'FINANCEIRO',
  '/financeiro/estrutura-dre',
  'layers',
  'DEFINICAO DA ESTRUTURA DO DRE E VINCULOS COM CONTAS',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_TELA WHERE CODIGO_TELA = 'FIN003_ESTRUTURA_DRE'), datetime('now')),
  (SELECT DATA_ATUALIZACAO FROM CORE_TELA WHERE CODIGO_TELA = 'FIN003_ESTRUTURA_DRE')
);

INSERT OR REPLACE INTO CORE_TELA (
  ID_TELA,
  CODIGO_TELA,
  NOME_TELA,
  MODULO,
  CAMINHO_ROTA,
  ICONE,
  DESCRICAO_TELA,
  ATIVA,
  DATA_CADASTRO,
  DATA_ATUALIZACAO
)
VALUES (
  COALESCE(
    (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN004_DRE'),
    (SELECT COALESCE(MAX(ID_TELA), 0) + 1 FROM CORE_TELA)
  ),
  'FIN004_DRE',
  'RELATORIO DRE',
  'FINANCEIRO',
  '/financeiro/dre',
  'file-digit',
  'RELATORIO DE DEMONSTRACAO DO RESULTADO DO EXERCICIO',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_TELA WHERE CODIGO_TELA = 'FIN004_DRE'), datetime('now')),
  (SELECT DATA_ATUALIZACAO FROM CORE_TELA WHERE CODIGO_TELA = 'FIN004_DRE')
);

INSERT INTO SEG_PERFIL_TELA (ID_PERFIL, ID_TELA, PODE_ACESSAR, PODE_CONSULTAR, PODE_EDITAR)
SELECT P.ID_PERFIL,
       T.ID_TELA,
       1, 1, 1
  FROM SEG_PERFIL P
  JOIN CORE_TELA T ON T.CODIGO_TELA IN ('FIN001_PLANO_CONTA', 'FIN002_CENTRO_CUSTO', 'FIN003_ESTRUTURA_DRE', 'FIN004_DRE')
 WHERE P.ID_PERFIL = 'PER-001'
   AND NOT EXISTS (
     SELECT 1 FROM SEG_PERFIL_TELA SPT
      WHERE SPT.ID_PERFIL = P.ID_PERFIL
        AND SPT.ID_TELA   = T.ID_TELA
   );
