-- Multiempresa para módulos financeiros
-- Alinhado ao padrão EMP_EMPRESA(ID_EMPRESA).
-- Se EMP_EMPRESA estiver ausente, substituir FK por string/uuid e remover o REFERENCES.

-- FIN_PLANO_CONTA
ALTER TABLE FIN_PLANO_CONTA ADD COLUMN ID_EMPRESA INTEGER REFERENCES EMP_EMPRESA(ID_EMPRESA);
UPDATE FIN_PLANO_CONTA SET ID_EMPRESA = EMPRESA_ID WHERE ID_EMPRESA IS NULL AND EMPRESA_ID IS NOT NULL;

DROP INDEX IF EXISTS IDX_FIN_PLANO_CONTA_EMPRESA;
DROP INDEX IF EXISTS UQ_FIN_PLANO_CONTA_EMPRESA_CODIGO;
DROP TRIGGER IF EXISTS TRG_FIN_PLANO_CONTA_EMPRESA_OBRIGATORIA;
DROP TRIGGER IF EXISTS TRG_FIN_PLANO_CONTA_EMPRESA_OBRIGATORIA_UPD;
DROP TRIGGER IF EXISTS TRG_FIN_PLANO_CONTA_EMPRESA_PAI;
DROP TRIGGER IF EXISTS TRG_FIN_PLANO_CONTA_EMPRESA_PAI_UPD;

CREATE INDEX IF NOT EXISTS IDX_FIN_PLANO_CONTA_EMPRESA ON FIN_PLANO_CONTA (ID_EMPRESA);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_FIN_PLANO_CONTA_EMPRESA_CODIGO
  ON FIN_PLANO_CONTA (ID_EMPRESA, FIN_PLANO_CONTA_CODIGO)
  WHERE ID_EMPRESA IS NOT NULL;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_PLANO_CONTA_EMPRESA_OBRIGATORIA
BEFORE INSERT ON FIN_PLANO_CONTA
WHEN NEW.ID_EMPRESA IS NULL
BEGIN
  SELECT RAISE(ABORT, 'FIN_PLANO_CONTA_REQUER_EMPRESA');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_PLANO_CONTA_EMPRESA_OBRIGATORIA_UPD
BEFORE UPDATE ON FIN_PLANO_CONTA
WHEN NEW.ID_EMPRESA IS NULL
BEGIN
  SELECT RAISE(ABORT, 'FIN_PLANO_CONTA_REQUER_EMPRESA');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_PLANO_CONTA_EMPRESA_PAI
BEFORE INSERT ON FIN_PLANO_CONTA
WHEN NEW.FIN_PLANO_CONTA_PAI_ID IS NOT NULL
  AND NEW.ID_EMPRESA IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM FIN_PLANO_CONTA PAI
     WHERE PAI.FIN_PLANO_CONTA_ID = NEW.FIN_PLANO_CONTA_PAI_ID
       AND (PAI.ID_EMPRESA IS NULL OR PAI.ID_EMPRESA <> NEW.ID_EMPRESA)
  )
BEGIN
  SELECT RAISE(ABORT, 'FIN_PLANO_CONTA_PAI_EMPRESA_DIFERENTE');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_PLANO_CONTA_EMPRESA_PAI_UPD
BEFORE UPDATE ON FIN_PLANO_CONTA
WHEN NEW.FIN_PLANO_CONTA_PAI_ID IS NOT NULL
  AND NEW.ID_EMPRESA IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM FIN_PLANO_CONTA PAI
     WHERE PAI.FIN_PLANO_CONTA_ID = NEW.FIN_PLANO_CONTA_PAI_ID
       AND (PAI.ID_EMPRESA IS NULL OR PAI.ID_EMPRESA <> NEW.ID_EMPRESA)
  )
BEGIN
  SELECT RAISE(ABORT, 'FIN_PLANO_CONTA_PAI_EMPRESA_DIFERENTE');
END;

-- FIN_CENTRO_CUSTO
ALTER TABLE FIN_CENTRO_CUSTO ADD COLUMN ID_EMPRESA INTEGER REFERENCES EMP_EMPRESA(ID_EMPRESA);
UPDATE FIN_CENTRO_CUSTO SET ID_EMPRESA = EMPRESA_ID WHERE ID_EMPRESA IS NULL AND EMPRESA_ID IS NOT NULL;

DROP INDEX IF EXISTS IDX_FIN_CENTRO_CUSTO_EMPRESA;
DROP INDEX IF EXISTS UQ_FIN_CENTRO_CUSTO_EMPRESA_CODIGO;
DROP TRIGGER IF EXISTS TRG_FIN_CENTRO_CUSTO_EMPRESA_OBRIGATORIA;
DROP TRIGGER IF EXISTS TRG_FIN_CENTRO_CUSTO_EMPRESA_OBRIGATORIA_UPD;
DROP TRIGGER IF EXISTS TRG_FIN_CENTRO_CUSTO_EMPRESA_PAI;
DROP TRIGGER IF EXISTS TRG_FIN_CENTRO_CUSTO_EMPRESA_PAI_UPD;

CREATE INDEX IF NOT EXISTS IDX_FIN_CENTRO_CUSTO_EMPRESA ON FIN_CENTRO_CUSTO (ID_EMPRESA);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_FIN_CENTRO_CUSTO_EMPRESA_CODIGO
  ON FIN_CENTRO_CUSTO (ID_EMPRESA, FIN_CENTRO_CUSTO_CODIGO)
  WHERE ID_EMPRESA IS NOT NULL;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_CENTRO_CUSTO_EMPRESA_OBRIGATORIA
BEFORE INSERT ON FIN_CENTRO_CUSTO
WHEN NEW.ID_EMPRESA IS NULL
BEGIN
  SELECT RAISE(ABORT, 'FIN_CENTRO_CUSTO_REQUER_EMPRESA');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_CENTRO_CUSTO_EMPRESA_OBRIGATORIA_UPD
BEFORE UPDATE ON FIN_CENTRO_CUSTO
WHEN NEW.ID_EMPRESA IS NULL
BEGIN
  SELECT RAISE(ABORT, 'FIN_CENTRO_CUSTO_REQUER_EMPRESA');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_CENTRO_CUSTO_EMPRESA_PAI
BEFORE INSERT ON FIN_CENTRO_CUSTO
WHEN NEW.FIN_CENTRO_CUSTO_PAI_ID IS NOT NULL
  AND NEW.ID_EMPRESA IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM FIN_CENTRO_CUSTO PAI
     WHERE PAI.FIN_CENTRO_CUSTO_ID = NEW.FIN_CENTRO_CUSTO_PAI_ID
       AND (PAI.ID_EMPRESA IS NULL OR PAI.ID_EMPRESA <> NEW.ID_EMPRESA)
  )
BEGIN
  SELECT RAISE(ABORT, 'FIN_CENTRO_CUSTO_PAI_EMPRESA_DIFERENTE');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_CENTRO_CUSTO_EMPRESA_PAI_UPD
BEFORE UPDATE ON FIN_CENTRO_CUSTO
WHEN NEW.FIN_CENTRO_CUSTO_PAI_ID IS NOT NULL
  AND NEW.ID_EMPRESA IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM FIN_CENTRO_CUSTO PAI
     WHERE PAI.FIN_CENTRO_CUSTO_ID = NEW.FIN_CENTRO_CUSTO_PAI_ID
       AND (PAI.ID_EMPRESA IS NULL OR PAI.ID_EMPRESA <> NEW.ID_EMPRESA)
  )
BEGIN
  SELECT RAISE(ABORT, 'FIN_CENTRO_CUSTO_PAI_EMPRESA_DIFERENTE');
END;

-- FIN_ESTRUTURA_DRE
ALTER TABLE FIN_ESTRUTURA_DRE ADD COLUMN ID_EMPRESA INTEGER REFERENCES EMP_EMPRESA(ID_EMPRESA);
UPDATE FIN_ESTRUTURA_DRE SET ID_EMPRESA = EMPRESA_ID WHERE ID_EMPRESA IS NULL AND EMPRESA_ID IS NOT NULL;

DROP INDEX IF EXISTS IDX_FIN_ESTRUTURA_DRE_EMPRESA;
DROP TRIGGER IF EXISTS TRG_FIN_ESTRUTURA_DRE_EMPRESA_OBRIGATORIA;
DROP TRIGGER IF EXISTS TRG_FIN_ESTRUTURA_DRE_EMPRESA_OBRIGATORIA_UPD;
DROP TRIGGER IF EXISTS TRG_FIN_ESTRUTURA_DRE_EMPRESA_PAI;
DROP TRIGGER IF EXISTS TRG_FIN_ESTRUTURA_DRE_EMPRESA_PAI_UPD;

CREATE INDEX IF NOT EXISTS IDX_FIN_ESTRUTURA_DRE_EMPRESA ON FIN_ESTRUTURA_DRE (ID_EMPRESA);

CREATE TRIGGER IF NOT EXISTS TRG_FIN_ESTRUTURA_DRE_EMPRESA_OBRIGATORIA
BEFORE INSERT ON FIN_ESTRUTURA_DRE
WHEN NEW.ID_EMPRESA IS NULL
BEGIN
  SELECT RAISE(ABORT, 'FIN_ESTRUTURA_DRE_REQUER_EMPRESA');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_ESTRUTURA_DRE_EMPRESA_OBRIGATORIA_UPD
BEFORE UPDATE ON FIN_ESTRUTURA_DRE
WHEN NEW.ID_EMPRESA IS NULL
BEGIN
  SELECT RAISE(ABORT, 'FIN_ESTRUTURA_DRE_REQUER_EMPRESA');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_ESTRUTURA_DRE_EMPRESA_PAI
BEFORE INSERT ON FIN_ESTRUTURA_DRE
WHEN NEW.FIN_ESTRUTURA_DRE_PAI_ID IS NOT NULL
  AND NEW.ID_EMPRESA IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM FIN_ESTRUTURA_DRE PAI
     WHERE PAI.FIN_ESTRUTURA_DRE_ID = NEW.FIN_ESTRUTURA_DRE_PAI_ID
       AND (PAI.ID_EMPRESA IS NULL OR PAI.ID_EMPRESA <> NEW.ID_EMPRESA)
  )
BEGIN
  SELECT RAISE(ABORT, 'FIN_ESTRUTURA_DRE_PAI_EMPRESA_DIFERENTE');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_ESTRUTURA_DRE_EMPRESA_PAI_UPD
BEFORE UPDATE ON FIN_ESTRUTURA_DRE
WHEN NEW.FIN_ESTRUTURA_DRE_PAI_ID IS NOT NULL
  AND NEW.ID_EMPRESA IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM FIN_ESTRUTURA_DRE PAI
     WHERE PAI.FIN_ESTRUTURA_DRE_ID = NEW.FIN_ESTRUTURA_DRE_PAI_ID
       AND (PAI.ID_EMPRESA IS NULL OR PAI.ID_EMPRESA <> NEW.ID_EMPRESA)
  )
BEGIN
  SELECT RAISE(ABORT, 'FIN_ESTRUTURA_DRE_PAI_EMPRESA_DIFERENTE');
END;

-- FIN_ESTRUTURA_DRE_CONTA
ALTER TABLE FIN_ESTRUTURA_DRE_CONTA ADD COLUMN ID_EMPRESA INTEGER REFERENCES EMP_EMPRESA(ID_EMPRESA);
UPDATE FIN_ESTRUTURA_DRE_CONTA SET ID_EMPRESA = EMPRESA_ID WHERE ID_EMPRESA IS NULL AND EMPRESA_ID IS NOT NULL;

DROP INDEX IF EXISTS IDX_FIN_ESTRUTURA_DRE_CONTA_EMPRESA;
DROP INDEX IF EXISTS UQ_FIN_ESTRUTURA_DRE_CONTA_EMPRESA;
DROP TRIGGER IF EXISTS TRG_FIN_ESTRUTURA_DRE_CONTA_EMPRESA_OBRIGATORIA;
DROP TRIGGER IF EXISTS TRG_FIN_ESTRUTURA_DRE_CONTA_EMPRESA_OBRIGATORIA_UPD;
DROP TRIGGER IF EXISTS TRG_FIN_ESTRUTURA_DRE_CONTA_COERENCIA;
DROP TRIGGER IF EXISTS TRG_FIN_ESTRUTURA_DRE_CONTA_COERENCIA_UPD;

CREATE INDEX IF NOT EXISTS IDX_FIN_ESTRUTURA_DRE_CONTA_EMPRESA ON FIN_ESTRUTURA_DRE_CONTA (ID_EMPRESA);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_FIN_ESTRUTURA_DRE_CONTA_EMPRESA
  ON FIN_ESTRUTURA_DRE_CONTA (ID_EMPRESA, FIN_ESTRUTURA_DRE_ID, FIN_PLANO_CONTA_ID)
  WHERE ID_EMPRESA IS NOT NULL;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_ESTRUTURA_DRE_CONTA_EMPRESA_OBRIGATORIA
BEFORE INSERT ON FIN_ESTRUTURA_DRE_CONTA
WHEN NEW.ID_EMPRESA IS NULL
BEGIN
  SELECT RAISE(ABORT, 'FIN_ESTRUTURA_DRE_CONTA_REQUER_EMPRESA');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_ESTRUTURA_DRE_CONTA_EMPRESA_OBRIGATORIA_UPD
BEFORE UPDATE ON FIN_ESTRUTURA_DRE_CONTA
WHEN NEW.ID_EMPRESA IS NULL
BEGIN
  SELECT RAISE(ABORT, 'FIN_ESTRUTURA_DRE_CONTA_REQUER_EMPRESA');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_ESTRUTURA_DRE_CONTA_COERENCIA
BEFORE INSERT ON FIN_ESTRUTURA_DRE_CONTA
WHEN NEW.ID_EMPRESA IS NOT NULL
  AND (
    (SELECT ID_EMPRESA FROM FIN_ESTRUTURA_DRE WHERE FIN_ESTRUTURA_DRE_ID = NEW.FIN_ESTRUTURA_DRE_ID) IS NULL
    OR (SELECT ID_EMPRESA FROM FIN_ESTRUTURA_DRE WHERE FIN_ESTRUTURA_DRE_ID = NEW.FIN_ESTRUTURA_DRE_ID) <> NEW.ID_EMPRESA
    OR (SELECT ID_EMPRESA FROM FIN_PLANO_CONTA WHERE FIN_PLANO_CONTA_ID = NEW.FIN_PLANO_CONTA_ID) IS NULL
    OR (SELECT ID_EMPRESA FROM FIN_PLANO_CONTA WHERE FIN_PLANO_CONTA_ID = NEW.FIN_PLANO_CONTA_ID) <> NEW.ID_EMPRESA
  )
BEGIN
  SELECT RAISE(ABORT, 'FIN_ESTRUTURA_DRE_CONTA_EMPRESA_MISMATCH');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_ESTRUTURA_DRE_CONTA_COERENCIA_UPD
BEFORE UPDATE ON FIN_ESTRUTURA_DRE_CONTA
WHEN NEW.ID_EMPRESA IS NOT NULL
  AND (
    (SELECT ID_EMPRESA FROM FIN_ESTRUTURA_DRE WHERE FIN_ESTRUTURA_DRE_ID = NEW.FIN_ESTRUTURA_DRE_ID) IS NULL
    OR (SELECT ID_EMPRESA FROM FIN_ESTRUTURA_DRE WHERE FIN_ESTRUTURA_DRE_ID = NEW.FIN_ESTRUTURA_DRE_ID) <> NEW.ID_EMPRESA
    OR (SELECT ID_EMPRESA FROM FIN_PLANO_CONTA WHERE FIN_PLANO_CONTA_ID = NEW.FIN_PLANO_CONTA_ID) IS NULL
    OR (SELECT ID_EMPRESA FROM FIN_PLANO_CONTA WHERE FIN_PLANO_CONTA_ID = NEW.FIN_PLANO_CONTA_ID) <> NEW.ID_EMPRESA
  )
BEGIN
  SELECT RAISE(ABORT, 'FIN_ESTRUTURA_DRE_CONTA_EMPRESA_MISMATCH');
END;

-- FIN_LANCAMENTO
ALTER TABLE FIN_LANCAMENTO ADD COLUMN ID_EMPRESA INTEGER REFERENCES EMP_EMPRESA(ID_EMPRESA);
UPDATE FIN_LANCAMENTO SET ID_EMPRESA = EMPRESA_ID WHERE ID_EMPRESA IS NULL AND EMPRESA_ID IS NOT NULL;

DROP INDEX IF EXISTS IDX_FIN_LANCAMENTO_EMPRESA;
DROP TRIGGER IF EXISTS TRG_FIN_LANCAMENTO_EMPRESA_OBRIGATORIA;
DROP TRIGGER IF EXISTS TRG_FIN_LANCAMENTO_EMPRESA_OBRIGATORIA_UPD;
DROP TRIGGER IF EXISTS TRG_FIN_LANCAMENTO_EMPRESA_COERENCIA;
DROP TRIGGER IF EXISTS TRG_FIN_LANCAMENTO_EMPRESA_COERENCIA_UPD;

CREATE INDEX IF NOT EXISTS IDX_FIN_LANCAMENTO_EMPRESA ON FIN_LANCAMENTO (ID_EMPRESA);

CREATE TRIGGER IF NOT EXISTS TRG_FIN_LANCAMENTO_EMPRESA_OBRIGATORIA
BEFORE INSERT ON FIN_LANCAMENTO
WHEN NEW.ID_EMPRESA IS NULL
BEGIN
  SELECT RAISE(ABORT, 'FIN_LANCAMENTO_REQUER_EMPRESA');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_LANCAMENTO_EMPRESA_OBRIGATORIA_UPD
BEFORE UPDATE ON FIN_LANCAMENTO
WHEN NEW.ID_EMPRESA IS NULL
BEGIN
  SELECT RAISE(ABORT, 'FIN_LANCAMENTO_REQUER_EMPRESA');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_LANCAMENTO_EMPRESA_COERENCIA
BEFORE INSERT ON FIN_LANCAMENTO
WHEN NEW.ID_EMPRESA IS NOT NULL
  AND (
    (SELECT ID_EMPRESA FROM FIN_PLANO_CONTA WHERE FIN_PLANO_CONTA_ID = NEW.FIN_PLANO_CONTA_ID) IS NULL
    OR (SELECT ID_EMPRESA FROM FIN_PLANO_CONTA WHERE FIN_PLANO_CONTA_ID = NEW.FIN_PLANO_CONTA_ID) <> NEW.ID_EMPRESA
    OR (NEW.FIN_CENTRO_CUSTO_ID IS NOT NULL AND (
      (SELECT ID_EMPRESA FROM FIN_CENTRO_CUSTO WHERE FIN_CENTRO_CUSTO_ID = NEW.FIN_CENTRO_CUSTO_ID) IS NULL
      OR (SELECT ID_EMPRESA FROM FIN_CENTRO_CUSTO WHERE FIN_CENTRO_CUSTO_ID = NEW.FIN_CENTRO_CUSTO_ID) <> NEW.ID_EMPRESA
    ))
  )
BEGIN
  SELECT RAISE(ABORT, 'FIN_LANCAMENTO_EMPRESA_MISMATCH');
END;

CREATE TRIGGER IF NOT EXISTS TRG_FIN_LANCAMENTO_EMPRESA_COERENCIA_UPD
BEFORE UPDATE ON FIN_LANCAMENTO
WHEN NEW.ID_EMPRESA IS NOT NULL
  AND (
    (SELECT ID_EMPRESA FROM FIN_PLANO_CONTA WHERE FIN_PLANO_CONTA_ID = NEW.FIN_PLANO_CONTA_ID) IS NULL
    OR (SELECT ID_EMPRESA FROM FIN_PLANO_CONTA WHERE FIN_PLANO_CONTA_ID = NEW.FIN_PLANO_CONTA_ID) <> NEW.ID_EMPRESA
    OR (NEW.FIN_CENTRO_CUSTO_ID IS NOT NULL AND (
      (SELECT ID_EMPRESA FROM FIN_CENTRO_CUSTO WHERE FIN_CENTRO_CUSTO_ID = NEW.FIN_CENTRO_CUSTO_ID) IS NULL
      OR (SELECT ID_EMPRESA FROM FIN_CENTRO_CUSTO WHERE FIN_CENTRO_CUSTO_ID = NEW.FIN_CENTRO_CUSTO_ID) <> NEW.ID_EMPRESA
    ))
  )
BEGIN
  SELECT RAISE(ABORT, 'FIN_LANCAMENTO_EMPRESA_MISMATCH');
END;

-- TODO: Registrar as telas FIN_DASHBOARD, FIN_LANCAMENTOS, FIN_PLANO_CONTA, FIN_CENTRO_CUSTO,
-- FIN_ESTRUTURA_DRE, FIN_ESTRUTURA_DRE_CONTA, FIN_DRE, FIN_OBJETIVOS e FIN_OBJETIVOS_SEMANAIS
-- em SEG_TELA quando a infraestrutura estiver disponível. O menu e HeaderBar já utilizam esses códigos.
