CREATE TABLE IF NOT EXISTS FIN_OBJETIVO (
  FIN_OBJETIVO_ID INTEGER PRIMARY KEY,
  FIN_OBJETIVO_TITULO TEXT NOT NULL,
  FIN_OBJETIVO_PERIODO TEXT NOT NULL CHECK (FIN_OBJETIVO_PERIODO IN ('Mensal', 'Trimestral', 'Anual')),
  FIN_OBJETIVO_META REAL NOT NULL DEFAULT 0,
  FIN_OBJETIVO_RESPONSAVEL TEXT,
  FIN_OBJETIVO_STATUS TEXT NOT NULL DEFAULT 'ativo' CHECK (FIN_OBJETIVO_STATUS IN ('ativo', 'inativo')),
  FIN_OBJETIVO_OBSERVACAO TEXT,
  FIN_OBJETIVO_CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  FIN_OBJETIVO_ATUALIZADO_EM TEXT,
  ID_EMPRESA INTEGER NOT NULL REFERENCES EMP_EMPRESA(ID_EMPRESA)
);

CREATE INDEX IF NOT EXISTS IDX_FIN_OBJETIVO_EMPRESA
  ON FIN_OBJETIVO (ID_EMPRESA);

CREATE TABLE IF NOT EXISTS FIN_OBJETIVO_SEMANAL (
  FIN_OBJETIVO_SEMANAL_ID INTEGER PRIMARY KEY,
  FIN_OBJETIVO_ID INTEGER NOT NULL REFERENCES FIN_OBJETIVO(FIN_OBJETIVO_ID),
  FIN_OBJETIVO_SEMANA TEXT NOT NULL,
  FIN_OBJETIVO_META_SEMANAL REAL NOT NULL DEFAULT 0,
  FIN_OBJETIVO_RESPONSAVEL TEXT,
  FIN_OBJETIVO_STATUS TEXT NOT NULL DEFAULT 'pendente' CHECK (FIN_OBJETIVO_STATUS IN ('pendente', 'andamento', 'concluido')),
  FIN_OBJETIVO_OBSERVACAO TEXT,
  FIN_OBJETIVO_SEMANAL_CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  FIN_OBJETIVO_SEMANAL_ATUALIZADO_EM TEXT,
  ID_EMPRESA INTEGER NOT NULL REFERENCES EMP_EMPRESA(ID_EMPRESA)
);

CREATE INDEX IF NOT EXISTS IDX_FIN_OBJETIVO_SEMANAL_EMPRESA
  ON FIN_OBJETIVO_SEMANAL (ID_EMPRESA);

CREATE INDEX IF NOT EXISTS IDX_FIN_OBJETIVO_SEMANAL_OBJETIVO
  ON FIN_OBJETIVO_SEMANAL (FIN_OBJETIVO_ID);
