-- Adiciona colunas referenciadas pelas APIs mas ausentes no schema original (058_FIN_BASE)

-- FIN_LANCAMENTO: campo de status (confirmado/pendente)
ALTER TABLE FIN_LANCAMENTO ADD COLUMN FIN_LANCAMENTO_STATUS TEXT NOT NULL DEFAULT 'confirmado';

-- FIN_CENTRO_CUSTO: campo de descrição/observações
ALTER TABLE FIN_CENTRO_CUSTO ADD COLUMN FIN_CENTRO_CUSTO_DESCRICAO TEXT;

-- FIN_ESTRUTURA_DRE: código, tipo e descrição
ALTER TABLE FIN_ESTRUTURA_DRE ADD COLUMN FIN_ESTRUTURA_DRE_CODIGO TEXT;
ALTER TABLE FIN_ESTRUTURA_DRE ADD COLUMN FIN_ESTRUTURA_DRE_TIPO TEXT;
ALTER TABLE FIN_ESTRUTURA_DRE ADD COLUMN FIN_ESTRUTURA_DRE_DESCRICAO TEXT;

-- Índice único para código da estrutura DRE por empresa
CREATE UNIQUE INDEX IF NOT EXISTS UQ_FIN_ESTRUTURA_DRE_EMPRESA_CODIGO
  ON FIN_ESTRUTURA_DRE (ID_EMPRESA, FIN_ESTRUTURA_DRE_CODIGO)
  WHERE ID_EMPRESA IS NOT NULL AND FIN_ESTRUTURA_DRE_CODIGO IS NOT NULL;
