-- Pró-labore: configuração e tabelas auxiliares
-- Usa EMPRESA_ID para consistência com demais tabelas FIN (058/060)

-- Configuração geral do pró-labore por empresa
CREATE TABLE IF NOT EXISTS FIN_PROLABORE_CONFIG (
  FIN_PROLABORE_CONFIG_ID INTEGER PRIMARY KEY,
  EMPRESA_ID INTEGER NOT NULL REFERENCES EMP_EMPRESA(ID_EMPRESA),
  FIN_PROLABORE_PERCENTUAL REAL NOT NULL DEFAULT 12.5,
  FIN_PROLABORE_SALDO_INICIAL REAL NOT NULL DEFAULT 0,
  FIN_PROLABORE_DATA_INICIO TEXT NOT NULL,
  FIN_PROLABORE_ATIVO INTEGER NOT NULL DEFAULT 1,
  FIN_PROLABORE_CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  FIN_PROLABORE_ATUALIZADO_EM TEXT,
  UNIQUE (EMPRESA_ID)
);

CREATE INDEX IF NOT EXISTS IDX_FIN_PROLABORE_CONFIG_EMPRESA
  ON FIN_PROLABORE_CONFIG (EMPRESA_ID);

-- Contas de receita EXCLUÍDAS do cálculo (ex: conta reserva, outras receitas)
CREATE TABLE IF NOT EXISTS FIN_PROLABORE_RECEITA_EXCLUIDA (
  FIN_PROLABORE_RECEITA_EXCLUIDA_ID INTEGER PRIMARY KEY,
  EMPRESA_ID INTEGER NOT NULL,
  FIN_PLANO_CONTA_ID INTEGER NOT NULL REFERENCES FIN_PLANO_CONTA(FIN_PLANO_CONTA_ID),
  FIN_PROLABORE_RECEITA_EXCLUIDA_CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (EMPRESA_ID, FIN_PLANO_CONTA_ID)
);

CREATE INDEX IF NOT EXISTS IDX_FIN_PROLABORE_RECEITA_EXCLUIDA_EMPRESA
  ON FIN_PROLABORE_RECEITA_EXCLUIDA (EMPRESA_ID);

-- Contas de despesa consideradas como pró-labore (débitos do extrato)
CREATE TABLE IF NOT EXISTS FIN_PROLABORE_DESPESA (
  FIN_PROLABORE_DESPESA_ID INTEGER PRIMARY KEY,
  EMPRESA_ID INTEGER NOT NULL,
  FIN_PLANO_CONTA_ID INTEGER NOT NULL REFERENCES FIN_PLANO_CONTA(FIN_PLANO_CONTA_ID),
  FIN_PROLABORE_DESPESA_CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (EMPRESA_ID, FIN_PLANO_CONTA_ID)
);

CREATE INDEX IF NOT EXISTS IDX_FIN_PROLABORE_DESPESA_EMPRESA
  ON FIN_PROLABORE_DESPESA (EMPRESA_ID);
