-- Tabela permanente de feriados (por empresa)
-- Armazena dia e mês (recorrente anualmente)
CREATE TABLE IF NOT EXISTS RH_FERIADO (
  RH_FERIADO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EMPRESA INTEGER NOT NULL,
  FERIADO_DIA INTEGER NOT NULL,
  FERIADO_MES INTEGER NOT NULL,
  FERIADO_DESCRICAO TEXT NOT NULL DEFAULT '',
  FERIADO_ATIVO INTEGER NOT NULL DEFAULT 1,
  CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (ID_EMPRESA, FERIADO_DIA, FERIADO_MES)
);
