-- Help para CAD004_RH_JORNADA (Cadastro de Jornadas de Trabalho e Feriados)

INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA,
  ID_TELA,
  OBJETIVO_TELA,
  QUANDO_UTILIZAR,
  DESCRICAO_PROCESSO,
  PASSO_A_PASSO,
  CAMPOS_OBRIGATORIOS,
  CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO,
  ERROS_COMUNS,
  ATIVA,
  DATA_CADASTRO,
  DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'CADASTRAR E GERENCIAR JORNADAS DE TRABALHO E FERIADOS DA EMPRESA.',
  'UTILIZAR PARA CRIAR OU EDITAR JORNADAS (HORARIOS DE ENTRADA/SAIDA, TOLERANCIA) E PARA GERENCIAR A TABELA DE FERIADOS.',
  'TELA RESPONSAVEL PELO CADASTRO DE JORNADAS DE TRABALHO E PELA GESTAO DE FERIADOS. AS JORNADAS DEFINEM OS HORARIOS PREVISTOS (MANHA E TARDE), TOLERANCIA EM MINUTOS E CARGA HORARIA. OS FERIADOS SAO CADASTRADOS POR DIA E MES (RECORRENTES ANUALMENTE) E IMPACTAM O CALCULO DO BANCO DE HORAS E PONTO.',
  '1) PARA JORNADAS: CLICAR EM NOVA JORNADA, PREENCHER DESCRICAO, HORARIOS DE ENTRADA/SAIDA (MANHA E TARDE), TOLERANCIA EM MINUTOS E CARGA HORARIA MENSAL. CLICAR EM SALVAR.\n2) PARA EDITAR UMA JORNADA: SELECIONAR NA TABELA E CLICAR EM EDITAR.\n3) PARA FERIADOS: CLICAR NO BOTAO GERENCIAR FERIADOS. UM MODAL SERA ABERTO COM A LISTA DE FERIADOS CADASTRADOS.\n4) PARA INCLUIR UM FERIADO: INFORMAR O DIA (1-31), O MES (1-12) E UMA DESCRICAO (EX: CONFRATERNIZACAO UNIVERSAL). CLICAR EM ADICIONAR.\n5) PARA EXCLUIR UM FERIADO: CLICAR NO BOTAO EXCLUIR AO LADO DO FERIADO DESEJADO E CONFIRMAR A EXCLUSAO.',
  'JORNADA: DESCRICAO, HORARIOS DE ENTRADA E SAIDA (MANHA E TARDE). FERIADO: DIA E MES.',
  'JORNADA: TOLERANCIA, CARGA HORARIA MENSAL. FERIADO: DESCRICAO DO FERIADO.',
  'AS JORNADAS SAO VINCULADAS AOS FUNCIONARIOS E UTILIZADAS NO CALCULO DO PONTO E BANCO DE HORAS PARA DETERMINAR A CARGA PREVISTA DIARIA. OS FERIADOS CADASTRADOS SAO APLICADOS AUTOMATICAMENTE NO LANCAMENTO DE PONTO (MARCADOS COMO FERIADO) E NO CALCULO DO BANCO DE HORAS: FERIADO NAO TRABALHADO NAO GERA HORAS DEVIDAS; FERIADO TRABALHADO GERA HORA EXTRA 100%.',
  'NAO PREENCHER OS HORARIOS DE ENTRADA E SAIDA, NAO INFORMAR DIA OU MES DO FERIADO, CADASTRAR FERIADO COM DIA INVALIDO (EX: DIA 31 PARA FEVEREIRO), OU ESQUECER DE CADASTRAR OS FERIADOS ANTES DE CALCULAR O BANCO DE HORAS.',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'CAD004_RH_JORNADA';
