-- Objetivos por conta (plano de contas ou centro de custo)
-- Cada linha armazena o % de crescimento/redução para uma conta específica

CREATE TABLE IF NOT EXISTS FIN_OBJETIVO_CONTA (
  FIN_OBJETIVO_CONTA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EMPRESA INTEGER NOT NULL,
  FIN_OBJETIVO_TIPO TEXT NOT NULL CHECK (FIN_OBJETIVO_TIPO IN ('PLANO_CONTAS', 'CENTRO_CUSTO')),
  FIN_CONTA_ID INTEGER NOT NULL,
  FIN_OBJETIVO_PERCENTUAL REAL NOT NULL DEFAULT 0,
  FIN_OBJETIVO_ANO INTEGER NOT NULL,
  CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (ID_EMPRESA, FIN_OBJETIVO_TIPO, FIN_CONTA_ID, FIN_OBJETIVO_ANO)
);
