-- Help documentation for Importação de Dados
INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA, ID_TELA,
  OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA,
  DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'IMPORTAR DADOS EM MASSA PARA O SISTEMA FINANCEIRO A PARTIR DE ARQUIVOS CSV.',
  'UTILIZAR QUANDO FOR NECESSARIO CADASTRAR DIVERSOS REGISTROS DE UMA SO VEZ: PLANO DE CONTAS, CENTROS DE CUSTO OU LANCAMENTOS DE CAIXA. IDEAL PARA MIGRACAO DE DADOS DE PLANILHAS EXISTENTES.',
  'TELA CENTRALIZADA DE IMPORTACAO DE DADOS FINANCEIROS. PERMITE SELECIONAR O TIPO DE DADOS (PLANO DE CONTAS, CENTRO DE CUSTO OU LANCAMENTOS), CARREGAR UM ARQUIVO CSV E MAPEAR AS COLUNAS DO ARQUIVO PARA OS CAMPOS DO SISTEMA. O SISTEMA DETECTA AUTOMATICAMENTE O SEPARADOR (VIRGULA, PONTO-E-VIRGULA OU TABULACAO) E TENTA MAPEAR AS COLUNAS AUTOMATICAMENTE PELO NOME.',
  '1) SELECIONAR O TIPO DE IMPORTACAO (PLANO DE CONTAS, CENTRO DE CUSTO OU LANCAMENTOS).\n2) SELECIONAR O ARQUIVO CSV COM OS DADOS.\n3) O SISTEMA EXIBE AS COLUNAS ENCONTRADAS NO ARQUIVO E TENTA MAPEAR AUTOMATICAMENTE.\n4) VERIFICAR E AJUSTAR O MAPEAMENTO DAS COLUNAS - CAMPOS COM * SAO OBRIGATORIOS.\n5) CONFERIR A PREVIA DOS DADOS (5 PRIMEIROS REGISTROS).\n6) CLICAR EM IMPORTAR PARA PROCESSAR TODOS OS REGISTROS.\n7) APOS A IMPORTACAO, O SISTEMA EXIBE O RESULTADO COM TOTAL IMPORTADOS E LISTA DE ERROS.',
  'PLANO DE CONTAS: CODIGO E NOME. CENTRO DE CUSTO: CODIGO E NOME. LANCAMENTOS: DATA, HISTORICO, CONTA (CODIGO OU NOME DO PLANO DE CONTAS) E VALOR.',
  'PLANO DE CONTAS: NATUREZA (RECEITA/DESPESA). CENTRO DE CUSTO: DESCRICAO. LANCAMENTOS: TIPO (ENTRADA/SAIDA), CENTRO DE CUSTO, DOCUMENTO.',
  'OS DADOS IMPORTADOS SAO INSERIDOS DIRETAMENTE NAS TABELAS DO SISTEMA. PLANO DE CONTAS E CENTROS DE CUSTO FICARAO DISPONIVEIS PARA USO NOS LANCAMENTOS. LANCAMENTOS IMPORTADOS SERAO CONTABILIZADOS NO DASHBOARD E RELATORIO DRE.',
  'ARQUIVO SEM CABECALHO NA PRIMEIRA LINHA. COLUNAS NAO MAPEADAS CORRETAMENTE. CODIGOS DUPLICADOS (PLANO DE CONTAS OU CENTRO DE CUSTO JA EXISTENTES). NOME DA CONTA NAO ENCONTRADO AO IMPORTAR LANCAMENTOS. FORMATO DE DATA DIFERENTE DO ESPERADO (USAR DD/MM/AAAA OU AAAA-MM-DD). VALOR COM FORMATO INVALIDO (USAR PONTO OU VIRGULA COMO DECIMAL).',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'FIN_IMPORTAR';

-- Help documentation for Resumo de Funcionários
INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA, ID_TELA,
  OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA,
  DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'CONSULTAR RESUMO CONSOLIDADO DE TODOS OS FUNCIONARIOS COM HORAS EXTRAS, FALTAS E EVOLUCAO MENSAL.',
  'UTILIZAR PARA TER UMA VISAO GERAL DE TODOS OS COLABORADORES SEM PRECISAR ACESSAR CADA UM INDIVIDUALMENTE. IDEAL PARA ACOMPANHAMENTO MENSAL E TOMADA DE DECISAO SOBRE BANCO DE HORAS.',
  'TELA DE CONSULTA QUE APRESENTA UM RESUMO EM FORMATO DE LISTA DE CADA FUNCIONARIO ATIVO, MOSTRANDO: HORAS EXTRAS (50% E 100%), HORAS DEVIDAS, FALTAS E SALDO DO BANCO DE HORAS. PERMITE FILTRAR POR PERIODO (ANO, MES INICIO E MES FIM) E POR NOME OU DEPARTAMENTO. AO EXPANDIR UM FUNCIONARIO, EXIBE A EVOLUCAO MENSAL DETALHADA.',
  '1) SELECIONAR O ANO E O INTERVALO DE MESES DESEJADO.\n2) OPCIONALMENTE BUSCAR POR NOME OU DEPARTAMENTO.\n3) A LISTA EXIBE TODOS OS FUNCIONARIOS ATIVOS COM RESUMO DE HORAS E FALTAS.\n4) CLICAR EM UM FUNCIONARIO PARA EXPANDIR E VER A EVOLUCAO MENSAL DETALHADA.\n5) OS CARDS NO TOPO MOSTRAM OS TOTAIS CONSOLIDADOS DE TODA A EQUIPE.',
  'ANO E PERIODO (MES INICIO E MES FIM).',
  'BUSCA POR NOME OU DEPARTAMENTO.',
  'DADOS SAO BASEADOS NOS FECHAMENTOS DO BANCO DE HORAS (PERIODOS FECHADOS). FUNCIONARIOS COM PERIODOS NAO FECHADOS PODEM APRESENTAR VALORES ZERADOS NA EVOLUCAO. ESTA TELA NAO ALTERA DADOS, APENAS CONSULTA.',
  'SELECIONAR UM PERIODO EM QUE NENHUM FECHAMENTO FOI REALIZADO (TODOS OS VALORES FICARAO ZERADOS). CONFUNDIR HORAS EXTRAS 50% (DIA UTIL) COM 100% (FERIADO/FIM DE SEMANA).',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'RH_RESUMO';

-- Update help for Lançamentos (Caixa) - removed summary cards, optimized for data entry
INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA, ID_TELA,
  OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA,
  DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'REGISTRAR, CONSULTAR E EDITAR LANCAMENTOS FINANCEIROS (ENTRADAS E SAIDAS DE CAIXA).',
  'UTILIZAR DIARIAMENTE PARA REGISTRAR MOVIMENTACOES FINANCEIRAS DA EMPRESA. PARA VISAO CONSOLIDADA DE ENTRADAS, SAIDAS E SALDO, ACESSAR O DASHBOARD EXECUTIVO.',
  'TELA OTIMIZADA PARA LANCAMENTO DE DADOS FINANCEIROS EM FORMATO DIVIDIDO: FORMULARIO DE ENTRADA A ESQUERDA E LISTA DE LANCAMENTOS A DIREITA. PERMITE FILTRAR POR PERIODO E BUSCA TEXTUAL. AO CLICAR EM UM LANCAMENTO NA LISTA, O FORMULARIO E PREENCHIDO PARA EDICAO.',
  '1) PREENCHER OS DADOS DO LANCAMENTO NO FORMULARIO (DATA, TIPO, HISTORICO, CONTA, VALOR).\n2) CLICAR EM SALVAR PARA REGISTRAR O LANCAMENTO.\n3) PARA EDITAR, CLICAR EM UM LANCAMENTO NA LISTA OU NO BOTAO EDITAR.\n4) PARA FILTRAR, USAR OS CAMPOS DE PERIODO E BUSCA ACIMA DA LISTA.\n5) NO MOBILE, A LISTA EXIBE OS LANCAMENTOS EM FORMATO DE CARDS.',
  'DATA, TIPO (ENTRADA OU SAIDA), HISTORICO, PLANO DE CONTA E VALOR.',
  'CENTRO DE CUSTO, DOCUMENTO (NUMERO OU REFERENCIA) E STATUS (CONFIRMADO/PENDENTE).',
  'LANCAMENTOS ALIMENTAM O DASHBOARD EXECUTIVO, O RELATORIO DRE E OS OBJETIVOS FINANCEIROS. VALORES POSITIVOS SAO ENTRADAS, NEGATIVOS SAO SAIDAS.',
  'NAO SELECIONAR O PLANO DE CONTAS. ESQUECER DE INFORMAR A DATA. CONFUNDIR O TIPO (ENTRADA/SAIDA) COM O SINAL DO VALOR.',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'FIN_LANCAMENTOS';

-- Update help for Objetivos Financeiros - % Global now uses open input field
INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA, ID_TELA,
  OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA,
  DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'DEFINIR METAS FINANCEIRAS BASEADAS NA MEDIA DO PERIODO COM PERCENTUAL DE CRESCIMENTO OU REDUCAO POR CONTA.',
  'UTILIZAR NO PLANEJAMENTO FINANCEIRO ANUAL OU PERIODICO PARA DEFINIR OBJETIVOS DE RECEITA E DESPESA POR CONTA OU CENTRO DE CUSTO.',
  'TELA DE PLANEJAMENTO FINANCEIRO QUE CALCULA A MEDIA MENSAL DE CADA CONTA (PLANO DE CONTAS OU CENTRO DE CUSTO) NO PERIODO SELECIONADO E PERMITE APLICAR PERCENTUAIS DE CRESCIMENTO OU REDUCAO PARA DEFINIR O OBJETIVO. O PERCENTUAL GLOBAL PERMITE APLICAR UM VALOR A TODAS AS CONTAS DE UMA VEZ (POSITIVO AUMENTA, NEGATIVO REDUZ). CADA CONTA PODE TER SEU PERCENTUAL INDIVIDUAL AJUSTADO.',
  '1) SELECIONAR A BASE (PLANO DE CONTAS OU CENTRO DE CUSTO).\n2) SELECIONAR O PERIODO DE REFERENCIA PARA CALCULO DA MEDIA (1, 3, 6 OU 12 MESES).\n3) DEFINIR O ANO DO OBJETIVO.\n4) PARA APLICAR UM PERCENTUAL A TODAS AS CONTAS: INFORMAR O VALOR NO CAMPO % GLOBAL E CLICAR EM APLICAR (POSITIVO = AUMENTO, NEGATIVO = REDUCAO).\n5) AJUSTAR INDIVIDUALMENTE O PERCENTUAL DE CADA CONTA NA COLUNA CRESC. %.\n6) CLICAR EM SALVAR OBJETIVOS PARA GRAVAR.',
  'BASE (PLANO DE CONTAS OU CENTRO DE CUSTO), PERIODO DE REFERENCIA E ANO DO OBJETIVO.',
  'PERCENTUAL GLOBAL, PERCENTUAL INDIVIDUAL POR CONTA.',
  'OS OBJETIVOS DEFINIDOS SAO UTILIZADOS COMO REFERENCIA NO ACOMPANHAMENTO FINANCEIRO E PODEM SER DETALHADOS EM OBJETIVOS SEMANAIS.',
  'NAO SALVAR APOS AJUSTAR OS PERCENTUAIS. SELECIONAR UM PERIODO DE REFERENCIA SEM LANCAMENTOS (MEDIA FICARA ZERADA). CONFUNDIR PERCENTUAL POSITIVO (AUMENTO) COM NEGATIVO (REDUCAO).',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'FIN_OBJETIVOS';

-- Update help for Dashboard - consolidated view
INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA, ID_TELA,
  OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA,
  DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'VISAO EXECUTIVA CONSOLIDADA DOS PRINCIPAIS INDICADORES FINANCEIROS E DE RECURSOS HUMANOS.',
  'UTILIZAR COMO PONTO DE PARTIDA PARA ACOMPANHAMENTO DIARIO DA SAUDE FINANCEIRA DA EMPRESA. CONCENTRA SALDO EM CAIXA, ENTRADAS, SAIDAS, INDICADORES DE PERFORMANCE E ALERTAS.',
  'PAINEL EXECUTIVO COM CARDS DE KPI (SALDO, ENTRADAS, SAIDAS, PESSOAL ATIVO), INDICADORES DE PERFORMANCE, MOVIMENTACAO POR EMPRESA, CONTAS VENCIDAS E LINKS RAPIDOS PARA AS PRINCIPAIS TELAS DO SISTEMA. O PERIODO PODE SER FILTRADO POR COMPETENCIA (MES/ANO).',
  '1) ACESSAR O DASHBOARD - OS DADOS SAO CARREGADOS AUTOMATICAMENTE.\n2) PARA FILTRAR POR PERIODO, SELECIONAR A COMPETENCIA NO CAMPO MES/ANO.\n3) ACOMPANHAR OS CARDS DE SALDO, ENTRADAS E SAIDAS NO TOPO.\n4) VERIFICAR OS INDICADORES DE PERFORMANCE E MOVIMENTACAO POR EMPRESA.\n5) ATENTAR AOS ALERTAS DE CONTAS VENCIDAS E SAIDAS PREVISTAS.\n6) USAR OS LINKS RAPIDOS PARA NAVEGAR PARA LANCAMENTOS, DRE OU OBJETIVOS.',
  'NENHUM - TELA DE CONSULTA.',
  'COMPETENCIA (MES/ANO) PARA FILTRAR O PERIODO.',
  'OS DADOS EXIBIDOS SAO CALCULADOS A PARTIR DOS LANCAMENTOS REGISTRADOS NO SISTEMA. ALTERACOES NOS LANCAMENTOS REFLETEM AUTOMATICAMENTE NO DASHBOARD.',
  'NENHUM LANCAMENTO CADASTRADO (DASHBOARD FICARA ZERADO). PERIODO SELECIONADO SEM MOVIMENTACAO.',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'FIN_DASHBOARD';
