-- Migration 071: Standardize all screen names to UPPERCASE without accents
-- Clean up duplicate entries, rename screens, fix modules

-- ============================================
-- 1. RENAME RH SCREENS
-- ============================================

-- Banco de Horas → FECHAMENTO PONTO
UPDATE CORE_TELA SET NOME_TELA = 'FECHAMENTO PONTO'
WHERE CODIGO_TELA = 'REL001_RH_BANCO_HORAS';

-- Consulta de Banco de Horas → CONSULTA PONTO
UPDATE CORE_TELA SET NOME_TELA = 'CONSULTA PONTO'
WHERE CODIGO_TELA = 'CONS001_RH_BANCO_HORAS';

-- Resumo de Funcionários → DASHBOARD RH
UPDATE CORE_TELA SET NOME_TELA = 'DASHBOARD RH'
WHERE CODIGO_TELA = 'RH_RESUMO';

-- Standardize other RH screens
UPDATE CORE_TELA SET NOME_TELA = 'CADASTRO DE JORNADA'
WHERE CODIGO_TELA = 'CAD004_RH_JORNADA';

UPDATE CORE_TELA SET NOME_TELA = 'CADASTRO DE FUNCIONARIO'
WHERE CODIGO_TELA = 'CAD005_RH_FUNCIONARIO';

UPDATE CORE_TELA SET NOME_TELA = 'LANCAMENTO DE PONTO'
WHERE CODIGO_TELA = 'LAN001_RH_PONTO';

-- ============================================
-- 2. STANDARDIZE FINANCEIRO SCREENS
-- ============================================

UPDATE CORE_TELA SET NOME_TELA = 'DASHBOARD FINANCEIRO'
WHERE CODIGO_TELA = 'FIN_DASHBOARD';

UPDATE CORE_TELA SET NOME_TELA = 'LANCAMENTOS (CAIXA)'
WHERE CODIGO_TELA = 'FIN_LANCAMENTOS';

UPDATE CORE_TELA SET NOME_TELA = 'PLANO DE CONTAS'
WHERE CODIGO_TELA = 'FIN001_PLANO_CONTA';

UPDATE CORE_TELA SET NOME_TELA = 'PLANO DE CONTAS'
WHERE CODIGO_TELA = 'FIN_PLANO_CONTA' OR CODIGO_TELA = 'CAD007_FIN_PLANO_CONTA';

UPDATE CORE_TELA SET NOME_TELA = 'CENTRO DE CUSTO'
WHERE CODIGO_TELA = 'FIN002_CENTRO_CUSTO';

UPDATE CORE_TELA SET NOME_TELA = 'CENTRO DE CUSTO'
WHERE CODIGO_TELA = 'FIN_CENTRO_CUSTO' OR CODIGO_TELA = 'CAD008_FIN_CENTRO_CUSTO' OR CODIGO_TELA = 'CAD012_FIN_CENTRO_CUSTO';

UPDATE CORE_TELA SET NOME_TELA = 'ESTRUTURA DO DRE'
WHERE CODIGO_TELA = 'FIN003_ESTRUTURA_DRE';

UPDATE CORE_TELA SET NOME_TELA = 'ESTRUTURA DO DRE'
WHERE CODIGO_TELA = 'FIN_ESTRUTURA_DRE' OR CODIGO_TELA = 'CAD009_FIN_ESTRUTURA_DRE' OR CODIGO_TELA = 'CAD013_FIN_ESTRUTURA_DRE';

UPDATE CORE_TELA SET NOME_TELA = 'RELATORIO DRE'
WHERE CODIGO_TELA = 'FIN004_DRE';

UPDATE CORE_TELA SET NOME_TELA = 'RELATORIO DRE'
WHERE CODIGO_TELA = 'FIN_DRE';

UPDATE CORE_TELA SET NOME_TELA = 'EXTRATO PRO-LABORE'
WHERE CODIGO_TELA = 'FIN_PROLABORE';

UPDATE CORE_TELA SET NOME_TELA = 'IMPORTACAO DE DADOS'
WHERE CODIGO_TELA = 'FIN_IMPORTAR';

-- ============================================
-- 3. OBJETIVOS - move to OBJETIVOS module
-- ============================================

UPDATE CORE_TELA SET NOME_TELA = 'OBJETIVOS FINANCEIROS', MODULO = 'OBJETIVOS'
WHERE CODIGO_TELA = 'FIN_OBJETIVOS';

UPDATE CORE_TELA SET NOME_TELA = 'OBJETIVOS FINANCEIROS', MODULO = 'OBJETIVOS'
WHERE CODIGO_TELA = 'CAD010_FIN_OBJETIVOS';

UPDATE CORE_TELA SET NOME_TELA = 'OBJETIVOS SEMANAIS', MODULO = 'OBJETIVOS'
WHERE CODIGO_TELA = 'FIN_OBJETIVOS_SEMANAIS';

UPDATE CORE_TELA SET NOME_TELA = 'OBJETIVOS SEMANAIS', MODULO = 'OBJETIVOS'
WHERE CODIGO_TELA = 'CAD011_FIN_OBJETIVOS_SEMANAIS';

-- ============================================
-- 4. STANDARDIZE CADASTROS
-- ============================================

UPDATE CORE_TELA SET NOME_TELA = 'SELECAO DE EMPRESA'
WHERE CODIGO_TELA = 'CAD001_EMP_SELECAO' OR CODIGO_TELA = 'CORE010_SELECAO_EMPRESA';

UPDATE CORE_TELA SET NOME_TELA = 'CADASTRO DE EMPRESA'
WHERE CODIGO_TELA = 'CAD001_CORE_EMPRESA' OR CODIGO_TELA = 'CAD002_EMP_EMPRESA';

UPDATE CORE_TELA SET NOME_TELA = 'CADASTRO DE DEPARTAMENTO'
WHERE CODIGO_TELA = 'CAD003_EMP_DEPARTAMENTO';

UPDATE CORE_TELA SET NOME_TELA = 'CADASTRO DE PERFIL DE ACESSO'
WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL';

-- ============================================
-- 5. DEACTIVATE DUPLICATE ENTRIES
-- ============================================

-- Deactivate duplicate Dashboard entries (keep FIN_DASHBOARD)
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA LIKE 'REL00%_FIN_DASHBOARD' AND CODIGO_TELA != 'FIN_DASHBOARD';

-- Deactivate duplicate Lancamentos entries (keep FIN_LANCAMENTOS)
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA LIKE 'LAN00%_FIN_LANCAMENTOS' AND CODIGO_TELA != 'FIN_LANCAMENTOS';

-- Deactivate duplicate Centro de Custo (keep FIN002_CENTRO_CUSTO and FIN_CENTRO_CUSTO)
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA IN ('CAD008_FIN_CENTRO_CUSTO', 'CAD012_FIN_CENTRO_CUSTO');

-- Deactivate duplicate Estrutura DRE (keep FIN003_ESTRUTURA_DRE and FIN_ESTRUTURA_DRE)
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA IN ('CAD009_FIN_ESTRUTURA_DRE', 'CAD013_FIN_ESTRUTURA_DRE');

-- Deactivate duplicate Objetivos entries (keep FIN_OBJETIVOS, FIN_OBJETIVOS_SEMANAIS)
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA IN ('CAD010_FIN_OBJETIVOS', 'CAD011_FIN_OBJETIVOS_SEMANAIS');

-- Deactivate duplicate DRE entries (keep FIN_DRE)
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA = 'FIN004_DRE';

-- Deactivate duplicate Plano de Contas (keep FIN_PLANO_CONTA or FIN001_PLANO_CONTA)
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA = 'CAD007_FIN_PLANO_CONTA';

-- ============================================
-- 6. UPDATE HELP CONTENT to reflect name changes
-- ============================================

-- Update Dashboard help to remove RH references, update for date range
UPDATE CORE_AJUDA_TELA SET
  OBJETIVO_TELA = 'VISAO EXECUTIVA CONSOLIDADA DOS PRINCIPAIS INDICADORES FINANCEIROS COM GRAFICOS E ANALISES.',
  QUANDO_UTILIZAR = 'UTILIZAR COMO PONTO DE PARTIDA PARA ACOMPANHAMENTO DIARIO DA SAUDE FINANCEIRA DA EMPRESA. ABAS DE RECEITAS, DESPESAS E GRAFICOS PARA ANALISE DETALHADA.',
  DESCRICAO_PROCESSO = 'PAINEL EXECUTIVO COM ABAS: VISAO GERAL (KPI, INDICADORES, ALERTAS), RECEITAS (EVOLUCAO, MEDIAS, GRAFICOS POR CONTA DE RECEITA), DESPESAS (EVOLUCAO, MEDIAS, GRAFICOS POR CONTA DE DESPESA) E GRAFICOS (CRUZAMENTO DE CONTAS, COMPARATIVOS COM SELECAO DE TIPO DE GRAFICO). FILTRO POR PERIODO COM DATAS INICIO E FIM.',
  PASSO_A_PASSO = '1) ACESSAR O DASHBOARD - DADOS CARREGADOS AUTOMATICAMENTE.\n2) SELECIONAR O PERIODO NAS DATAS INICIO E FIM.\n3) ABA VISAO GERAL: CARDS KPI, INDICADORES DE PERFORMANCE E ALERTAS.\n4) ABA RECEITAS: EVOLUCAO MENSAL, MEDIAS E GRAFICOS DE RECEITA COM SELECAO DE TIPO (BARRA, LINHA, PIZZA).\n5) ABA DESPESAS: EVOLUCAO MENSAL, MEDIAS E GRAFICOS DE DESPESA.\n6) ABA GRAFICOS: CRUZAR CONTAS DO DRE E PLANO DE CONTAS PARA ANALISE COMPARATIVA.',
  CAMPOS_OPCIONAIS = 'DATA INICIO, DATA FIM, TIPO DE GRAFICO, CONTAS PARA CRUZAMENTO.',
  DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN_DASHBOARD');

-- Update RH_RESUMO help to reflect new name
UPDATE CORE_AJUDA_TELA SET
  OBJETIVO_TELA = 'CONSULTAR DASHBOARD CONSOLIDADO DE TODOS OS FUNCIONARIOS COM HORAS EXTRAS, FALTAS E EVOLUCAO MENSAL.',
  DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'RH_RESUMO');

-- Update Banco de Horas help to reflect FECHAMENTO PONTO
UPDATE CORE_AJUDA_TELA SET
  OBJETIVO_TELA = 'REALIZAR O FECHAMENTO DE PONTO DOS FUNCIONARIOS, CONSOLIDANDO HORAS EXTRAS, FALTAS E SALDOS.',
  DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'REL001_RH_BANCO_HORAS');

-- Update Consulta help to reflect CONSULTA PONTO
UPDATE CORE_AJUDA_TELA SET
  OBJETIVO_TELA = 'CONSULTAR HISTORICO DE PONTO E FECHAMENTOS REALIZADOS PARA CADA FUNCIONARIO.',
  DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'CONS001_RH_BANCO_HORAS');

-- Update Objetivos help
UPDATE CORE_AJUDA_TELA SET
  DESCRICAO_PROCESSO = 'TELA DE PLANEJAMENTO FINANCEIRO QUE CALCULA A MEDIA MENSAL DE CADA CONTA NO PERIODO SELECIONADO (MES INICIO A MES FIM) E PERMITE APLICAR PERCENTUAIS DE CRESCIMENTO OU REDUCAO. O PERCENTUAL GLOBAL E O ANO FICAM AO LADO DOS FILTROS. CADA CONTA PODE TER SEU PERCENTUAL INDIVIDUAL.',
  DATA_ATUALIZACAO = datetime('now')
WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN_OBJETIVOS');
