-- Migration 072: Add help for Objetivos Semanais, deactivate duplicate DRE screen, add menu ordering

-- ============================================
-- 1. DEACTIVATE DUPLICATE REL001_FIN_DRE
-- ============================================
-- The sidebar uses FIN_DRE for DRE screen. REL001_FIN_DRE is a duplicate without help content.
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA = 'REL001_FIN_DRE';

-- ============================================
-- 2. STANDARDIZE MODULO VALUES TO MATCH SIDEBAR SECTIONS
-- ============================================
-- CADASTROS section (was CORE, EMPRESA, SEGURANCA)
UPDATE CORE_TELA SET MODULO = 'CADASTROS'
WHERE CODIGO_TELA IN ('CORE010_SELECAO_EMPRESA', 'CAD001_EMP_SELECAO', 'CAD002_EMP_EMPRESA', 'CAD001_CORE_EMPRESA', 'CAD003_EMP_DEPARTAMENTO', 'CAD006_SEG_PERFIL');

-- RECURSOS HUMANOS section (was RH)
UPDATE CORE_TELA SET MODULO = 'RECURSOS HUMANOS'
WHERE CODIGO_TELA IN ('RH_RESUMO', 'CAD004_RH_JORNADA', 'CAD005_RH_FUNCIONARIO', 'LAN001_RH_PONTO', 'REL001_RH_BANCO_HORAS', 'CONS001_RH_BANCO_HORAS');

-- FINANCEIRO and OBJETIVOS already correct

-- ============================================
-- 3. ADD ORDEM_MENU COLUMN FOR MENU ORDERING
-- ============================================
ALTER TABLE CORE_TELA ADD COLUMN ORDEM_MENU INTEGER DEFAULT 999;

-- Set order matching sidebar menu structure
-- CADASTROS section (100-199)
UPDATE CORE_TELA SET ORDEM_MENU = 110 WHERE CODIGO_TELA = 'CAD002_EMP_EMPRESA' OR CODIGO_TELA = 'CAD001_CORE_EMPRESA';
UPDATE CORE_TELA SET ORDEM_MENU = 120 WHERE CODIGO_TELA = 'CAD003_EMP_DEPARTAMENTO';
UPDATE CORE_TELA SET ORDEM_MENU = 130 WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL';

-- RECURSOS HUMANOS section (200-299)
UPDATE CORE_TELA SET ORDEM_MENU = 200 WHERE CODIGO_TELA = 'RH_RESUMO';
UPDATE CORE_TELA SET ORDEM_MENU = 210 WHERE CODIGO_TELA = 'CAD004_RH_JORNADA';
UPDATE CORE_TELA SET ORDEM_MENU = 220 WHERE CODIGO_TELA = 'CAD005_RH_FUNCIONARIO';
UPDATE CORE_TELA SET ORDEM_MENU = 230 WHERE CODIGO_TELA = 'LAN001_RH_PONTO';
UPDATE CORE_TELA SET ORDEM_MENU = 240 WHERE CODIGO_TELA = 'REL001_RH_BANCO_HORAS';
UPDATE CORE_TELA SET ORDEM_MENU = 250 WHERE CODIGO_TELA = 'CONS001_RH_BANCO_HORAS';

-- FINANCEIRO section (300-399)
UPDATE CORE_TELA SET ORDEM_MENU = 300 WHERE CODIGO_TELA = 'FIN_DASHBOARD';
UPDATE CORE_TELA SET ORDEM_MENU = 310 WHERE CODIGO_TELA = 'FIN_LANCAMENTOS';
UPDATE CORE_TELA SET ORDEM_MENU = 320 WHERE CODIGO_TELA = 'FIN_PLANO_CONTA' OR CODIGO_TELA = 'FIN001_PLANO_CONTA';
UPDATE CORE_TELA SET ORDEM_MENU = 330 WHERE CODIGO_TELA = 'FIN_CENTRO_CUSTO' OR CODIGO_TELA = 'FIN002_CENTRO_CUSTO';
UPDATE CORE_TELA SET ORDEM_MENU = 340 WHERE CODIGO_TELA = 'FIN_ESTRUTURA_DRE' OR CODIGO_TELA = 'FIN003_ESTRUTURA_DRE';
UPDATE CORE_TELA SET ORDEM_MENU = 350 WHERE CODIGO_TELA = 'FIN_DRE';
UPDATE CORE_TELA SET ORDEM_MENU = 360 WHERE CODIGO_TELA = 'FIN_PROLABORE';
UPDATE CORE_TELA SET ORDEM_MENU = 370 WHERE CODIGO_TELA = 'FIN_IMPORTAR';

-- OBJETIVOS section (400-499)
UPDATE CORE_TELA SET ORDEM_MENU = 400 WHERE CODIGO_TELA = 'FIN_OBJETIVOS';
UPDATE CORE_TELA SET ORDEM_MENU = 410 WHERE CODIGO_TELA = 'FIN_OBJETIVOS_SEMANAIS';

-- AJUDA section (900)
UPDATE CORE_TELA SET ORDEM_MENU = 900 WHERE CODIGO_TELA = 'HELP000_CORE_AJUDA';

-- ============================================
-- 4. CREATE HELP FOR OBJETIVOS SEMANAIS
-- ============================================
INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA, ID_TELA,
  OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA,
  DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'PLANEJAR E ACOMPANHAR ENTREGAS SEMANAIS ALINHADAS AOS OBJETIVOS FINANCEIROS DA EMPRESA.',
  'UTILIZAR SEMANALMENTE PARA DESDOBRAR OS OBJETIVOS FINANCEIROS EM METAS SEMANAIS COM RESPONSAVEIS E PRAZOS. PERMITE ACOMPANHAR O STATUS DE CADA ENTREGA E GARANTIR QUE O PLANEJAMENTO ESTA SENDO CUMPRIDO.',
  'TELA DE PLANEJAMENTO SEMANAL QUE DEPENDE DOS OBJETIVOS FINANCEIROS CADASTRADOS. CADA SEMANA PODE TER METAS ESPECIFICAS, RESPONSAVEIS E STATUS DE ACOMPANHAMENTO. A LISTA SO CARREGA QUANDO EXISTEM OBJETIVOS FINANCEIROS CADASTRADOS. PERMITE FILTRAR POR NOME DO OBJETIVO E VISUALIZAR STATUS (PENDENTE, EM ANDAMENTO, CONCLUIDO).',
  '1) ACESSAR A TELA DE OBJETIVOS SEMANAIS.\n2) VERIFICAR SE EXISTEM OBJETIVOS FINANCEIROS CADASTRADOS (PRE-REQUISITO).\n3) CLICAR EM NOVA SEMANA PARA CRIAR UM PLANEJAMENTO SEMANAL.\n4) SELECIONAR O OBJETIVO FINANCEIRO RELACIONADO.\n5) SELECIONAR A SEMANA (SEMANA 1 A 4).\n6) INFORMAR A META SEMANAL (VALOR OU PERCENTUAL).\n7) INFORMAR O RESPONSAVEL (EQUIPE OU PESSOA).\n8) DEFINIR O STATUS INICIAL (PENDENTE, EM ANDAMENTO OU CONCLUIDO).\n9) OPCIONALMENTE, ADICIONAR OBSERVACOES SOBRE DEPENDENCIAS E ENTREGAVEIS.\n10) CLICAR EM SALVAR SEMANA.',
  'OBJETIVO FINANCEIRO (SELECAO), SEMANA, META SEMANAL.',
  'RESPONSAVEL, STATUS, OBSERVACOES.',
  'OS OBJETIVOS SEMANAIS SAO UM DESDOBRAMENTO DOS OBJETIVOS FINANCEIROS. ALTERACOES NOS OBJETIVOS FINANCEIROS PODEM IMPACTAR A RELEVANCIA DAS METAS SEMANAIS. ACOMPANHAR O STATUS SEMANALMENTE PARA GARANTIR ALINHAMENTO COM O PLANO FINANCEIRO.',
  'TENTAR CRIAR SEMANA SEM TER OBJETIVOS FINANCEIROS CADASTRADOS. NAO ATUALIZAR O STATUS CONFORME AS ENTREGAS SAO REALIZADAS. CONFUNDIR META EM PERCENTUAL COM META EM VALOR MONETARIO.',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'FIN_OBJETIVOS_SEMANAIS';

-- ============================================
-- 5. CREATE HELP FOR DRE (FIN_DRE) if missing
-- ============================================
INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA, ID_TELA,
  OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA,
  DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'GERAR E CONSULTAR O DEMONSTRATIVO DE RESULTADO DO EXERCICIO (DRE) DA EMPRESA.',
  'UTILIZAR MENSALMENTE OU QUANDO NECESSARIO PARA AVALIAR O RESULTADO FINANCEIRO DA EMPRESA EM UM PERIODO ESPECIFICO. PERMITE COMPARAR RECEITAS E DESPESAS ORGANIZADAS PELA ESTRUTURA DO DRE CADASTRADA.',
  'RELATORIO QUE APRESENTA AS RECEITAS E DESPESAS DA EMPRESA ORGANIZADAS CONFORME A ESTRUTURA DO DRE PREVIAMENTE CADASTRADA. OS VALORES SAO CALCULADOS A PARTIR DOS LANCAMENTOS FINANCEIROS DO PERIODO SELECIONADO, CLASSIFICADOS PELAS CONTAS VINCULADAS A CADA LINHA DO DRE.',
  '1) ACESSAR O RELATORIO DRE.\n2) SELECIONAR O PERIODO DESEJADO (MES E ANO).\n3) O SISTEMA CALCULA E APRESENTA O DRE COM BASE NOS LANCAMENTOS DO PERIODO.\n4) VERIFICAR AS LINHAS DE RECEITA, DEDUCOES, CUSTOS E DESPESAS.\n5) ANALISAR O RESULTADO LIQUIDO DO PERIODO.',
  'PERIODO (MES E ANO).',
  'NENHUM - TELA DE CONSULTA.',
  'O DRE DEPENDE DA ESTRUTURA DO DRE CADASTRADA E DOS LANCAMENTOS FINANCEIROS REGISTRADOS NO PERIODO. LANCAMENTOS SEM CONTA VINCULADA A ESTRUTURA DO DRE NAO APARECERAO NO RELATORIO.',
  'PERIODO SEM LANCAMENTOS (DRE FICARA ZERADO). ESTRUTURA DO DRE NAO CADASTRADA. CONTAS DO PLANO NAO VINCULADAS A ESTRUTURA DO DRE.',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'FIN_DRE';
