-- Migration 073: Clean up duplicate CORE_TELA entries
-- Keep only screens that are actually used in the application code (Sidebar + pages)
--
-- ACTIVE SCREENS (21 total):
-- CADASTROS: CAD001_EMP_SELECAO, CAD002_EMP_EMPRESA, CAD003_EMP_DEPARTAMENTO, CAD006_SEG_PERFIL
-- RH: RH_RESUMO, CAD004_RH_JORNADA, CAD005_RH_FUNCIONARIO, LAN001_RH_PONTO, REL001_RH_BANCO_HORAS, CONS001_RH_BANCO_HORAS
-- FINANCEIRO: FIN_DASHBOARD, FIN_LANCAMENTOS, FIN_PLANO_CONTA, FIN_CENTRO_CUSTO, FIN_ESTRUTURA_DRE, FIN_DRE, FIN_PROLABORE, FIN_IMPORTAR
-- OBJETIVOS: FIN_OBJETIVOS, FIN_OBJETIVOS_SEMANAIS
-- SISTEMA: HELP000_CORE_AJUDA

-- ============================================
-- DEACTIVATE ALL UNUSED DUPLICATES
-- ============================================

-- FIN001_PLANO_CONTA is duplicate of FIN_PLANO_CONTA (used in Sidebar + page)
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA = 'FIN001_PLANO_CONTA';

-- FIN002_CENTRO_CUSTO is duplicate of FIN_CENTRO_CUSTO (used in Sidebar + page)
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA = 'FIN002_CENTRO_CUSTO';

-- FIN003_ESTRUTURA_DRE is duplicate of FIN_ESTRUTURA_DRE (used in Sidebar + page)
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA = 'FIN003_ESTRUTURA_DRE';

-- CAD001_CORE_EMPRESA is legacy code, replaced by CAD002_EMP_EMPRESA
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA = 'CAD001_CORE_EMPRESA';

-- CORE010_SELECAO_EMPRESA is legacy code, replaced by CAD001_EMP_SELECAO
UPDATE CORE_TELA SET ATIVA = 0
WHERE CODIGO_TELA = 'CORE010_SELECAO_EMPRESA';

-- ============================================
-- TRANSFER HELP CONTENT FROM DUPLICATES TO ACTIVE ENTRIES
-- ============================================

-- Copy help from FIN001_PLANO_CONTA to FIN_PLANO_CONTA if FIN_PLANO_CONTA has no help
INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA, OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA, DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN_PLANO_CONTA'),
  A.OBJETIVO_TELA, A.QUANDO_UTILIZAR, A.DESCRICAO_PROCESSO,
  A.PASSO_A_PASSO, A.CAMPOS_OBRIGATORIOS, A.CAMPOS_OPCIONAIS,
  A.REFLEXOS_PROCESSO, A.ERROS_COMUNS, 1, datetime('now'), datetime('now')
FROM CORE_AJUDA_TELA A
WHERE A.ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN001_PLANO_CONTA')
  AND NOT EXISTS (
    SELECT 1 FROM CORE_AJUDA_TELA WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN_PLANO_CONTA')
  );

-- Copy help from FIN002_CENTRO_CUSTO to FIN_CENTRO_CUSTO if FIN_CENTRO_CUSTO has no help
INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA, OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA, DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN_CENTRO_CUSTO'),
  A.OBJETIVO_TELA, A.QUANDO_UTILIZAR, A.DESCRICAO_PROCESSO,
  A.PASSO_A_PASSO, A.CAMPOS_OBRIGATORIOS, A.CAMPOS_OPCIONAIS,
  A.REFLEXOS_PROCESSO, A.ERROS_COMUNS, 1, datetime('now'), datetime('now')
FROM CORE_AJUDA_TELA A
WHERE A.ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN002_CENTRO_CUSTO')
  AND NOT EXISTS (
    SELECT 1 FROM CORE_AJUDA_TELA WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN_CENTRO_CUSTO')
  );

-- Copy help from FIN003_ESTRUTURA_DRE to FIN_ESTRUTURA_DRE if FIN_ESTRUTURA_DRE has no help
INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA, OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA, DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN_ESTRUTURA_DRE'),
  A.OBJETIVO_TELA, A.QUANDO_UTILIZAR, A.DESCRICAO_PROCESSO,
  A.PASSO_A_PASSO, A.CAMPOS_OBRIGATORIOS, A.CAMPOS_OPCIONAIS,
  A.REFLEXOS_PROCESSO, A.ERROS_COMUNS, 1, datetime('now'), datetime('now')
FROM CORE_AJUDA_TELA A
WHERE A.ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN003_ESTRUTURA_DRE')
  AND NOT EXISTS (
    SELECT 1 FROM CORE_AJUDA_TELA WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN_ESTRUTURA_DRE')
  );

-- ============================================
-- ENSURE MODULO IS SET CORRECTLY ON ALL ACTIVE SCREENS
-- ============================================
UPDATE CORE_TELA SET MODULO = 'CADASTROS'
WHERE CODIGO_TELA = 'CAD001_EMP_SELECAO' AND (MODULO IS NULL OR MODULO != 'CADASTROS');

UPDATE CORE_TELA SET MODULO = 'CADASTROS'
WHERE CODIGO_TELA = 'CAD002_EMP_EMPRESA' AND (MODULO IS NULL OR MODULO != 'CADASTROS');

UPDATE CORE_TELA SET MODULO = 'CADASTROS'
WHERE CODIGO_TELA = 'CAD003_EMP_DEPARTAMENTO' AND (MODULO IS NULL OR MODULO != 'CADASTROS');

UPDATE CORE_TELA SET MODULO = 'CADASTROS'
WHERE CODIGO_TELA = 'CAD006_SEG_PERFIL' AND (MODULO IS NULL OR MODULO != 'CADASTROS');

UPDATE CORE_TELA SET MODULO = 'RECURSOS HUMANOS'
WHERE CODIGO_TELA IN ('RH_RESUMO', 'CAD004_RH_JORNADA', 'CAD005_RH_FUNCIONARIO', 'LAN001_RH_PONTO', 'REL001_RH_BANCO_HORAS', 'CONS001_RH_BANCO_HORAS')
  AND (MODULO IS NULL OR MODULO != 'RECURSOS HUMANOS');

UPDATE CORE_TELA SET MODULO = 'FINANCEIRO'
WHERE CODIGO_TELA IN ('FIN_DASHBOARD', 'FIN_LANCAMENTOS', 'FIN_PLANO_CONTA', 'FIN_CENTRO_CUSTO', 'FIN_ESTRUTURA_DRE', 'FIN_DRE', 'FIN_PROLABORE', 'FIN_IMPORTAR')
  AND (MODULO IS NULL OR MODULO != 'FINANCEIRO');

UPDATE CORE_TELA SET MODULO = 'OBJETIVOS'
WHERE CODIGO_TELA IN ('FIN_OBJETIVOS', 'FIN_OBJETIVOS_SEMANAIS')
  AND (MODULO IS NULL OR MODULO != 'OBJETIVOS');
