-- Migration 076: Insert FIN_PLANO_CONTA into CORE_TELA
-- The record was never created. Migration 059 created FIN001_PLANO_CONTA,
-- migration 073 deactivated it assuming FIN_PLANO_CONTA existed, but it didn't.

-- Create the missing FIN_PLANO_CONTA entry
INSERT OR IGNORE INTO CORE_TELA (
  ID_TELA,
  CODIGO_TELA,
  NOME_TELA,
  MODULO,
  CAMINHO_ROTA,
  ICONE,
  DESCRICAO_TELA,
  ATIVA,
  DATA_CADASTRO,
  DATA_ATUALIZACAO
)
VALUES (
  (SELECT COALESCE(MAX(ID_TELA), 0) + 1 FROM CORE_TELA),
  'FIN_PLANO_CONTA',
  'PLANO DE CONTAS',
  'FINANCEIRO',
  '/financeiro/plano-conta',
  'hierarchy',
  'CADASTRO E MANUTENCAO DO PLANO DE CONTAS FINANCEIRO',
  1,
  datetime('now'),
  datetime('now')
);

-- Grant permissions to all existing profiles that have other FIN screens
INSERT OR IGNORE INTO SEG_PERFIL_TELA (ID_PERFIL, ID_TELA, PODE_ACESSAR, PODE_CONSULTAR, PODE_EDITAR)
SELECT DISTINCT SPT.ID_PERFIL,
       (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN_PLANO_CONTA'),
       1, 1, 1
FROM SEG_PERFIL_TELA SPT
JOIN CORE_TELA CT ON CT.ID_TELA = SPT.ID_TELA
WHERE CT.MODULO = 'FINANCEIRO'
  AND SPT.PODE_ACESSAR = 1
  AND NOT EXISTS (
    SELECT 1 FROM SEG_PERFIL_TELA X
    WHERE X.ID_PERFIL = SPT.ID_PERFIL
      AND X.ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN_PLANO_CONTA')
  );

-- Copy help content from the deactivated FIN001_PLANO_CONTA if FIN_PLANO_CONTA has no help
INSERT OR IGNORE INTO CORE_AJUDA_TELA (
  ID_TELA, OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA, DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN_PLANO_CONTA'),
  A.OBJETIVO_TELA, A.QUANDO_UTILIZAR, A.DESCRICAO_PROCESSO,
  A.PASSO_A_PASSO, A.CAMPOS_OBRIGATORIOS, A.CAMPOS_OPCIONAIS,
  A.REFLEXOS_PROCESSO, A.ERROS_COMUNS, 1, datetime('now'), datetime('now')
FROM CORE_AJUDA_TELA A
WHERE A.ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN001_PLANO_CONTA')
  AND NOT EXISTS (
    SELECT 1 FROM CORE_AJUDA_TELA WHERE ID_TELA = (SELECT ID_TELA FROM CORE_TELA WHERE CODIGO_TELA = 'FIN_PLANO_CONTA')
  );
