-- Conta padrao de receita e despesa no cadastro de pessoa (cliente/fornecedor)
ALTER TABLE CAD_PESSOA ADD COLUMN CAD_PESSOA_CONTA_RECEITA_ID INTEGER REFERENCES FIN_PLANO_CONTA(FIN_PLANO_CONTA_ID);
ALTER TABLE CAD_PESSOA ADD COLUMN CAD_PESSOA_CONTA_DESPESA_ID INTEGER REFERENCES FIN_PLANO_CONTA(FIN_PLANO_CONTA_ID);

-- Placa do veiculo nos lancamentos de receita
ALTER TABLE FIN_LANCAMENTO ADD COLUMN FIN_LANCAMENTO_PLACA TEXT;
