-- Corrigir CHECK constraint de FIN_OBJETIVO_CONTA para permitir ESTRUTURA_DRE
-- E adicionar colunas de periodo em FIN_OBJETIVO

-- 1. Recriar FIN_OBJETIVO_CONTA sem CHECK restritivo no tipo
CREATE TABLE IF NOT EXISTS FIN_OBJETIVO_CONTA_NEW (
  FIN_OBJETIVO_CONTA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EMPRESA INTEGER NOT NULL,
  FIN_OBJETIVO_TIPO TEXT NOT NULL,
  FIN_CONTA_ID INTEGER NOT NULL,
  FIN_OBJETIVO_PERCENTUAL REAL NOT NULL DEFAULT 0,
  FIN_OBJETIVO_ANO INTEGER NOT NULL,
  CRIADO_EM TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (ID_EMPRESA, FIN_OBJETIVO_TIPO, FIN_CONTA_ID, FIN_OBJETIVO_ANO)
);

INSERT OR IGNORE INTO FIN_OBJETIVO_CONTA_NEW (FIN_OBJETIVO_CONTA_ID, ID_EMPRESA, FIN_OBJETIVO_TIPO, FIN_CONTA_ID, FIN_OBJETIVO_PERCENTUAL, FIN_OBJETIVO_ANO, CRIADO_EM)
  SELECT FIN_OBJETIVO_CONTA_ID, ID_EMPRESA, FIN_OBJETIVO_TIPO, FIN_CONTA_ID, FIN_OBJETIVO_PERCENTUAL, FIN_OBJETIVO_ANO, CRIADO_EM
  FROM FIN_OBJETIVO_CONTA;

DROP TABLE IF EXISTS FIN_OBJETIVO_CONTA;

ALTER TABLE FIN_OBJETIVO_CONTA_NEW RENAME TO FIN_OBJETIVO_CONTA;

-- 2. Adicionar colunas de periodo ao FIN_OBJETIVO
ALTER TABLE FIN_OBJETIVO ADD COLUMN FIN_OBJETIVO_TIPO_PERIODO TEXT;
ALTER TABLE FIN_OBJETIVO ADD COLUMN FIN_OBJETIVO_REF_PERIODO TEXT;
ALTER TABLE FIN_OBJETIVO ADD COLUMN FIN_OBJETIVO_VALOR_TOTAL REAL DEFAULT 0;
