-- Tabela de auditoria para registrar alterações e exclusões em lançamentos
CREATE TABLE IF NOT EXISTS AUDIT_LOG (
  AUDIT_LOG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EMPRESA_ID INTEGER NOT NULL,
  TABELA TEXT NOT NULL,
  REGISTRO_ID INTEGER NOT NULL,
  OPERACAO TEXT NOT NULL CHECK (OPERACAO IN ('INSERT', 'UPDATE', 'DELETE')),
  DADOS_ANTES TEXT,
  DADOS_DEPOIS TEXT,
  DESCRICAO TEXT,
  DATA_OPERACAO TEXT DEFAULT (datetime('now')),
  REVERTIDO INTEGER DEFAULT 0,
  DATA_REVERSAO TEXT,
  FOREIGN KEY (EMPRESA_ID) REFERENCES EMP_EMPRESA(ID_EMPRESA)
);

CREATE INDEX IF NOT EXISTS IDX_AUDIT_LOG_EMPRESA ON AUDIT_LOG(EMPRESA_ID);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_LOG_TABELA ON AUDIT_LOG(TABELA);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_LOG_REGISTRO ON AUDIT_LOG(TABELA, REGISTRO_ID);
CREATE INDEX IF NOT EXISTS IDX_AUDIT_LOG_DATA ON AUDIT_LOG(DATA_OPERACAO);
