-- Register Log de Auditoria screen
INSERT OR IGNORE INTO CORE_TELA (CODIGO_TELA, NOME_TELA, MODULO, CAMINHO_ROTA, ICONE, DESCRICAO_TELA, ATIVA, DATA_CADASTRO)
VALUES ('LOG_AUDITORIA', 'Log de Auditoria', 'CADASTROS', '/cadastros/log', 'scroll-text', 'CONSULTA DE LOGS DE ALTERACAO E EXCLUSAO DE REGISTROS DO SISTEMA', 1, datetime('now'));

-- Grant access to admin profile (PER-001)
INSERT INTO SEG_PERFIL_TELA (ID_PERFIL, ID_TELA, PODE_ACESSAR, PODE_CONSULTAR, PODE_EDITAR)
SELECT P.ID_PERFIL, T.ID_TELA, 1, 1, 1
  FROM SEG_PERFIL P
  JOIN CORE_TELA T ON T.CODIGO_TELA = 'LOG_AUDITORIA'
 WHERE P.ID_PERFIL = 'PER-001'
   AND NOT EXISTS (
     SELECT 1 FROM SEG_PERFIL_TELA SPT
      WHERE SPT.ID_PERFIL = P.ID_PERFIL
        AND SPT.ID_TELA   = T.ID_TELA
   );
