-- Help documentation for Log de Auditoria
INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA, ID_TELA,
  OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA,
  DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'CONSULTAR E RASTREAR TODAS AS ALTERACOES E EXCLUSOES REALIZADAS EM LANCAMENTOS FINANCEIROS E REGISTROS DE PONTO.',
  'UTILIZAR QUANDO FOR NECESSARIO VERIFICAR HISTORICO DE ALTERACOES EM LANCAMENTOS, IDENTIFICAR QUEM E QUANDO FEZ DETERMINADA MODIFICACAO, OU REVERTER UM LANCAMENTO EXCLUIDO OU ALTERADO INDEVIDAMENTE.',
  'TELA DE CONSULTA QUE EXIBE O HISTORICO COMPLETO DE OPERACOES (ALTERACAO E EXCLUSAO) REALIZADAS EM LANCAMENTOS FINANCEIROS E REGISTROS DE PONTO. CADA REGISTRO MOSTRA OS DADOS ANTES E DEPOIS DA ALTERACAO, PERMITINDO COMPARACAO E, QUANDO POSSIVEL, A REVERSAO DA OPERACAO PARA RESTAURAR OS DADOS ORIGINAIS.',
  '1) ACESSAR A TELA DE LOG DE AUDITORIA NO MENU CADASTROS.\n2) FILTRAR POR TABELA (LANCAMENTOS FINANCEIROS OU PONTO), PERIODO OU OPERACAO (ALTERACAO/EXCLUSAO).\n3) VISUALIZAR OS REGISTROS DE AUDITORIA COM DADOS ANTES E DEPOIS DA ALTERACAO.\n4) PARA REVERTER UMA OPERACAO: EXPANDIR O REGISTRO E CLICAR EM REVERTER.\n5) O SISTEMA RESTAURARA OS DADOS ORIGINAIS DO REGISTRO.',
  'NENHUM - TELA DE CONSULTA.',
  'FILTROS POR TABELA, PERIODO, TIPO DE OPERACAO.',
  'AO REVERTER UMA EXCLUSAO, O LANCAMENTO ORIGINAL E RESTAURADO NA TABELA DE ORIGEM. AO REVERTER UMA ALTERACAO, OS DADOS ANTERIORES SAO RESTAURADOS. CADA REVERSAO TAMBEM E REGISTRADA NO LOG.',
  'TENTAR REVERTER UM REGISTRO QUE JA FOI REVERTIDO. REVERTER LANCAMENTO CUJO PLANO DE CONTAS OU CENTRO DE CUSTO JA FOI EXCLUIDO.',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'LOG_AUDITORIA';

-- Update help for Importação de Dados with new Lançamentos Financeiros tab
INSERT OR REPLACE INTO CORE_AJUDA_TELA (
  ID_AJUDA, ID_TELA,
  OBJETIVO_TELA, QUANDO_UTILIZAR, DESCRICAO_PROCESSO,
  PASSO_A_PASSO, CAMPOS_OBRIGATORIOS, CAMPOS_OPCIONAIS,
  REFLEXOS_PROCESSO, ERROS_COMUNS, ATIVA,
  DATA_CADASTRO, DATA_ATUALIZACAO
)
SELECT
  (SELECT ID_AJUDA FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA),
  T.ID_TELA,
  'IMPORTAR DADOS EM MASSA PARA O SISTEMA FINANCEIRO A PARTIR DE ARQUIVOS CSV. INCLUI IMPORTACAO DE PLANO DE CONTAS, CENTROS DE CUSTO, LANCAMENTOS E LANCAMENTOS FINANCEIROS COM EDICAO PREVIA.',
  'UTILIZAR QUANDO FOR NECESSARIO CADASTRAR DIVERSOS REGISTROS DE UMA SO VEZ. A ABA LANCAMENTOS FINANCEIROS PERMITE IMPORTAR LANCAMENTOS COM CAMPOS DETALHADOS (CODIGO, DESCRICAO, CONTA, NATUREZA, VALOR, DATA DE INCLUSAO, DATA DE MOVIMENTO E PLACA DO VEICULO COM DETECCAO AUTOMATICA).',
  'TELA COM DUAS ABAS: IMPORTACAO DE ARQUIVOS (PLANO DE CONTAS, CENTRO DE CUSTO E LANCAMENTOS) E IMPORTACAO DE LANCAMENTOS FINANCEIROS. NA ABA DE LANCAMENTOS FINANCEIROS, APOS O UPLOAD DO CSV, O SISTEMA APRESENTA UMA GRADE EDITAVEL COM TODOS OS REGISTROS MAPEADOS, PERMITINDO EDITAR, INCLUIR OU EXCLUIR REGISTROS ANTES DA IMPORTACAO FINAL. O SISTEMA DETECTA AUTOMATICAMENTE PLACAS DE VEICULOS NA DESCRICAO (FORMATOS ABC1234 E ABC-1D23) E PREENCHE O CAMPO PLACA.',
  '1) SELECIONAR A ABA DESEJADA (IMPORTACAO DE ARQUIVOS OU LANCAMENTOS FINANCEIROS).\n2) PARA LANCAMENTOS FINANCEIROS: SELECIONAR O ARQUIVO CSV.\n3) MAPEAR AS COLUNAS DO ARQUIVO PARA OS CAMPOS DO SISTEMA.\n4) CONFERIR A GRADE EDITAVEL COM TODOS OS REGISTROS IMPORTADOS.\n5) EDITAR, INCLUIR OU EXCLUIR REGISTROS CONFORME NECESSARIO.\n6) VERIFICAR SE AS PLACAS FORAM DETECTADAS AUTOMATICAMENTE NAS DESCRICOES.\n7) VALORES SAO SEMPRE POSITIVOS - O TIPO DA CONTA (RECEITA/DESPESA) DETERMINA O SINAL.\n8) CLICAR EM IMPORTAR PARA PROCESSAR TODOS OS REGISTROS.',
  'DESCRICAO, CONTA (PLANO DE CONTAS), VALOR, DATA DE MOVIMENTO (COMPETENCIA).',
  'CODIGO, NATUREZA (AUTO-DETECTADA PELA CONTA), DATA DE INCLUSAO (DEFAULT HOJE), PLACA (AUTO-DETECTADA DA DESCRICAO).',
  'OS LANCAMENTOS IMPORTADOS SAO INSERIDOS NA TABELA FIN_LANCAMENTO COM LOG DE AUDITORIA. VALORES POSITIVOS SAO RECEITAS E NEGATIVOS SAO DESPESAS (DETERMINADO AUTOMATICAMENTE PELA NATUREZA DA CONTA). PLACAS DETECTADAS FICAM VINCULADAS AO LANCAMENTO PARA RASTREABILIDADE.',
  'ARQUIVO SEM CABECALHO. CONTA NAO ENCONTRADA NO PLANO DE CONTAS. VALOR COM FORMATO INVALIDO. PLACA NAO DETECTADA EM DESCRICOES COM FORMATO NAO PADRAO.',
  1,
  COALESCE((SELECT DATA_CADASTRO FROM CORE_AJUDA_TELA WHERE ID_TELA = T.ID_TELA), datetime('now')),
  datetime('now')
FROM CORE_TELA T
WHERE T.CODIGO_TELA = 'FIN_IMPORTAR';
